boostcampwm2023/iOS06-FlipMate

iOS/FlipMate/FlipMate/Application/SceneDelegate.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/Model/LoginType.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewController/LoginViewController.swift
close #29 
- 구글 로그인 버튼 UI 구현
- 애플 로그인 버튼 UI 구현
- 비로그인 버튼 UI 구현
- 로고 UI 구현
[버튼 다크모드 대응](https://yeim.notion.site/UIButton-Title-d74b5df592274ff1a0c32789c146b4f3?pvs=4)
다크모드, 라이트모드의 이미지의 사이즈 크기가 달라서 현재 크기가 다르게 보이는 이슈가 있습니다.
이슈 목록에 추가해놓도록 하겠습니다~~!!
| 다크모드 | 라이트모드  |
| -------- | -------- |
| ![simulator_screenshot_1034AAF7-367B-474A-8E94-6B478DE59602](https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/3501f5f3-dae8-45e8-8bcc-8e72a7ae4145)     | ![simulator_screenshot_E78F8F52-D275-4F53-985D-80492CA19736](https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/fc205bab-9837-49ea-adc5-5e2739065336)     |
=> [iOS#29] 로그인 UI 구현

iOS/FlipMate/FlipMate/Presentation/LoginScene/Model/LoginType.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewController/LoginViewController.swift
closed #50 
- Login 버튼 layer color 수정
- FlipMateColor사용하여 UIColor 수정
- FlipMateFont사용하여 UIFont 수정
- BaseViewController 상속하여 LoginViewController 수정
- LoginType description -> buttonTitle로 네이밍 수정
- BaseViewController을 상속하다보니 ConfigureUI 메소드에 접근 제어를 걸 수 없다는 문제가 생겼습니다... 해당 방식에 대해서 같이 의논하면 좋을 것 같습니다.
=> [iOS#50] 로그인 화면 리팩토링

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Presentation/TimerScene/View/CategoryListCollectionViewCell.swift
close #80 
- CollectionView에 재사용될 Cell Layout 구현
1. 시간 라벨 같은 경우 `59:59`, `01:59:59` 처럼 1시간을 초과한 경우 조금 문제가 있습니다. 텍스트라벨을 오른쪽 정렬하는 기능을 search 하면 쉽게 될 듯 합니다.
2. 추후 카테고리 선택 기능 구현 시 그림자 기능을 Cell 자체에 만들어 두는 것은 부자연스럽겠지요??
+)
추가로 왼쪽에 색깔 라벨은 SFSymbol `"circle.fill"`  사용하였는 데, 색깔 바꾸는 것이 조금 까다로운 것 같네요
=> [iOS#80] CategoryListCollectionView 파일 생성

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj
close #88 
pbxproj 파일의 중괄호를 안닫아 발생한 오류
=> [iOS#88] pbxproj 수정

BE/package-lock.json, BE/package.json, BE/src/auth/auth.controller.ts, BE/src/auth/auth.module.ts, BE/src/auth/auth.service.ts, BE/src/auth/guard/bearer-token.guard.ts, BE/src/main.ts, BE/src/users/decorator/user.decorator.ts, BE/src/users/dto/create-user.dto.ts, BE/src/users/users.controller.ts, BE/src/users/users.service.ts
close #121 
CreateUserDto에 아래와 같이 PickType을 사용했습니다.
```ts
import { PickType } from '@nestjs/mapped-types';
import { UsersModel } from '../entity/users.entity';
export class CreateUserDto extends PickType(UsersModel, [
'nickname',
'email',
'image_url',
]) {}
```
이유는 CreateUserDto는 결국 User 엔티티 값 내에서 사용하는데 이를 위한 Validator를 중복적으로 작성하는게 과연 맞을까? 라는 의구심이 들어서 찾아보니 기존 ts의 유틸리티 타입을 활용하여 작성하는 경우도 많더라고요 여기서 UpdateUserDto는 아래처럼 작성한답니다.
```ts
import { PartialType } from "@nestjs/mapped-types";
import { CreateUserDto } from "./create-user.dto";
// UpdateUserDto는 CreateUserDto와 인터페이스 동일하나 필수 값이 아니다
export class UpdateUserDto extends PartialType(CreateUserDto) {}
```
유저 생성과정에서 중복되면 어떡하지? 일단 쿼리를 날리기전에 확인을 해야하나? 라는 생각에 아래와 같이 작성했다.
```ts
async createUser(user: RegisterUserDto): Promise<UsersModel> {
const …
```
=> [BE#121] 인가된 사용자인지 확인

iOS/FlipMate/FlipMate/Common/Color/FlipMateColor.swift, iOS/FlipMate/FlipMate/Presentation/TabBarViewController.swift, iOS/FlipMate/FlipMate/Resources/Assets.xcassets/FilpMateColor/TabBarColor.colorset/Contents.json, iOS/FlipMate/FlipMate/Resources/Assets.xcassets/FilpMateColor/TabBarLayerColor.colorset/Contents.json
closed #99 
- TabBar 백그라운드 컬러에 대응되는 컬러 Asset 추가
- TabBar Layer BorderColor에 대응되는 컬러 Asset 추가
- 탭 전환 시 타이머 버튼이 지속적으로 생성되는 이슈 수정
기존에 AssetCatalog로 Dynamic Color를 생성해서 다크모드에 대응했었지만
CGColor는 컴파일 시점에 다크모드와 라이트모드 대응이 되지만 런타임 시점에 사용자 테마가 바뀌게 되면 자동으로 적용이 안되는 문제가 있었습니다. traitCollectionDidChange 메소드를 오버라이드하여 사용자 디바이스의 테마가 바뀔 때 마다 컬러를 다시 설정해주었습니다.
https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/880cfa7e-524a-4f48-9e03-68147c71e25f
=> [iOS#99] 탭바 다크모드 대응

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Presentation/TimerScene/Model/CategorySettingSection.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/View/CategorySettingFooterView.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/CategorySettingViewController.swift, iOS/FlipMate/FlipMate/Presentation/Utils/Extensions/UICollectionReusableView++Extension.swift, iOS/FlipMate/FlipMate/Presentation/Utils/Extensions/UICollectionView++Extension.swift, iOS/FlipMate/FlipMate/Presentation/Utils/Extensions/UICollectionViewCell++Extension.swift
closed #112 
- 카테고리 관리 collectionView 구현
- 추가 버튼은 footerView를 사용하여 구현
- UICollectionVIewCell, UICollectionReusableView 재사용성을 높이기 위해 제네릭을 사용하여 register, dequeue 메소드 구현
| 라이트모드 | 다크모드 |
| -------- | -------- |
| <img width="376" alt="image" src="https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/c18ac947-d9e4-46ca-83d2-e8d63b4a4d9f"> | <img width="392" alt="image" src="https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/c77a2622-0e07-4812-8dc2-75dea1dc5eae"> |
dataSource을 ViewModel이 가지고 있으면 ViewModel이 UIKit에 의존하게 되어 UIKit에 독립적인 ViewModel로 관리하기 위해 dataSource을 ViewController가 가지고 있도록 구현했습니다.
추후에 ViewModel을 통해서 dataSource의 snapshot을 변경하도록 구현하면 될 것 같습니다.
- cell과 ReusableView을 register, dequeue할때마다 타입 캐스팅을 줄이고, 재사용이 높은 작업을 위해 해당 로직을 제네릭을 통해 메소드로 구현해놨습니다. …
=> [iOS#112] 카테고리 관리 화면 UI 구현

iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift
close #62 
- 관리 버튼의 이미지 이름과 타이틀 리터럴 상수화
- 타이머 시간의 초기 시간 리터럴 상수화
- 상수를 담는 타입의 위치를 고민해 보았는데, 타이머 뷰 컨트롤러에서만 사용하기 때문에 타이머 뷰 컨트롤러 내부에 private한 enum을 선언해 주었습니다.
=> [iOS#62] 타이머 뷰 컨트롤러 상수 처리

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Data/Network/DataMapping/TimerScene/TimerStartRequestDTO.swift, iOS/FlipMate/FlipMate/NetworkService/BaseURL.swift, iOS/FlipMate/FlipMate/NetworkService/EndPoint.swift, iOS/FlipMate/FlipMate/NetworkService/HTTPHeader.swift, iOS/FlipMate/FlipMate/NetworkService/Provider.swift, iOS/FlipMate/FlipMate/NetworkService/Requestable.swift
closed #149 
- Swagger 문서와 DTO 맞추기
- HTTP 헤더 필드 Content-Type 추가
- baseURL 파일 분리하여 생성
이미 추상화된 EndPoint을 한 번 더 추상화한다는 느낌이 생들어서 해당 부분은 일단 구현하지 않았습니다.
위의 방식대로 추상화하는 것보단 기능에 맞는 EndPoint을 생성해주는 객체를 만들어서 관리하는 방식이 현재 저희가 구현한 네트워크 레이어에 더 적합한 것 같다는 생각이 들었습니다.
이미 method와 path가 추상화된 프로토콜이 Requestable인데 추상화에 추상화를 한 번 더 해주는 느낌입니다.
=> [iOS#148] 네트워크 기능 개선

.github/workflows/be-pre-production-workflow.yaml, BE/src/main.ts
- cd 일단 했는데 잘 되는지 테스트를 해야합니다..
preproduction 브랜치의 BE 폴더에 푸쉬가 발생하면 액션이 발생하도록 했습니다.
```ts
configService.get<boolean>('SSL');
```
위 코드가 계속 string 값을 뽑아오길래 그냥 string으로 비교하도록 바꿨습니다
포트 환경변수로 바꿔서 개발용 / 가배포용으로 나눌 예정입니다
개발용 포트 : 3333
가배포용 포트: 3000
=> [BE#152] preproduction cd

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Presentation/TimerScene/View/CategoryColorSelectView.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/View/CategoryTitleTextView.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/View/CustomTextView.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/CategoryModifyViewController.swift
close #113 
UI만 구현했습니다. 
1. 기존 피그마 디자인 색상 섹션에 이름이 그대로 들어가는 데, 구현해보니 조금 어색해서 Hex를 넣으려고 하는데 어떻게 생각하시나요?
2. 추후 화면 연결 시 Navigation Controller를 사용할 지, 아니면 사용 안 할 지 확실하지 않아서 Navigation Bar를 구체화해서 넣지는 않았습니다. 다만 로직은 모두 구현해두었기에 NavigationController를 사용하지 않는다면 NavigationBar Component만 추가하면 될 것 같습니다. 만약 사용하면 코드 그대로 두셔도 됩니다.
3. Cell 말고 모두 Custom View로 구현했습니다.
=> [iOS#113] 카테고리 추가 / 수정 UI 구현

BE/src/app.controller.ts, BE/src/auth/auth.controller.ts, BE/src/auth/auth.service.ts, BE/src/auth/google.strategy.ts, BE/src/categories/categories.controller.ts, BE/src/main.ts, BE/src/mates/mates.controller.ts, BE/src/study-logs/study-logs.controller.ts, BE/src/users/dto/update-user.dto.ts, BE/src/users/entity/users.entity.ts, BE/src/users/users.controller.ts, BE/src/users/users.service.ts
- fetch 요청을 통해 구글 서버에 access_token 보내기
- 새로운 사용자는 is_member false 반환
- 사용자는 base64 닉네임으로 미리 생성 후 유저정보 변경하도록 유도
- 사용자를 미리 생성해두고 닉네임 변경하도록 유도 한다면 닉네임 중복은 어떻게 피하지? -> '이메일 + 타입'을 base64로 인코딩
=> [BE#155] 아이폰용 로그인

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Application/AppFlowCoordinator.swift, iOS/FlipMate/FlipMate/Application/DIContainer/AppDIContainer.swift, iOS/FlipMate/FlipMate/Application/DIContainer/CategoryDIContainer.swift, iOS/FlipMate/FlipMate/Application/DIContainer/LoginDIContainer.swift, iOS/FlipMate/FlipMate/Application/DIContainer/TabBarDIContainer.swift, iOS/FlipMate/FlipMate/Application/DIContainer/TimerSceneDIContainer.swift, iOS/FlipMate/FlipMate/Application/SceneDelegate.swift, iOS/FlipMate/FlipMate/Data/Repositories/DefaultCategoryRepository.swift, iOS/FlipMate/FlipMate/Data/Repositories/Utils/DefaultGoogleAuthRepository.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/Flows/LoginFlowCoordinator.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewController/LoginViewController.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewModel/LoginViewModel.swift, iOS/FlipMate/FlipMate/Presentation/TabBar/Flows/TabBarFlowCoordinator.swift, iOS/FlipMate/FlipMate/Presentation/TabBar/ViewController/TabBarViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/Flows/CategorySettingCoordinator.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/Flows/TimerFlowCoordinator.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/View/CategorySettingFooterView.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/CategoryModifyViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/CategorySettingViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/CategoryViewModel.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/TimerViewModel.swift
- AppDIContainer 구현
- AppFlowCoordinator 구현
- 각각 화면에 필요한 DIContainer와 FlowCoordinator 구현
- 로그인 화면에서 탭바컨트롤러로 전환 시 로그인 VC 및 관련 객체 매모리 해제되도록 수정
Coordinator 패턴에 대해서는 어느정도 이해가 되었는데 어떤식으로 적용을 해야할지 상당히 해맸습니다.
일단 기초를 MVVM + Clean Archiecture 예제 코드를 참고해서 구현했습니다. 
각각의 화면 전환이 필요한 ViewController인 경우 FlowCoordinator가 화면 전환을 담당해주고
해당 FlowCoordinator에서 ViewController에 의존성을 주입하는 부분은 DI Container가 담당하고 있습니다.
먼저, 기초가 되는 AppFlowCoordinator와 AppDIContainer을 구현하고 AppFlowCoordinator와 AppDIContainer을 SceneDelegate에서 사용하여 로그인 여부에 따라 LoginViewController와 TabBarController을 보여주도록 했습니다.
화면 전환이 필요한 ViewController마다 FlowCoordinator을 생성하였고, 해당 FlowCoordinator의 start() 메소드를 통해 해당 ViewController을 띄우고, 화면 전환이 필요한 경우에는 DI Container에서 화면을 전환하고 싶은 ViewController의 DI Container와 FlowCoordinator을 생성하고 해당 FlowCoordinator을 통해 화면을 …
=> [iOS#201] DI Conatiner 및 Coordinator 패턴 적용

BE/package-lock.json, BE/package.json, BE/src/users/interface/greeneye.interface.ts, BE/src/users/users.service.ts
close #200 
- clova greeneye api를 활용한 이미지 유해성 검사
- 현재 이미지의 url을 이용해 검사 요청 api를 활용하도록 구현했는데, base64 인코딩 이미지 바이트로도 활용할 수 있습니다.
- api 요청을 보내면 각 label 별로(normal, adult, sexy, porn) score를 리턴해주는데, 일단 normal이 0.5보다 크면 정상 이미지로 처리하도록 했습니다.
[api 공식 문서](https://api.ncloud-docs.com/docs/ai-application-service-greeneye-custom-api)
=> [BE#200]이미지 유해성 검사 기능 추가

BE/src/categories/categories.entity.ts, BE/src/study-logs/study-logs.entity.ts
close #224 
```ts
@ManyToOne(() => Categories, (categories) => categories.study_logs, {
onDelete: 'SET NULL',
})
```
SET NULL 옵션을 통해 카테고리 삭제에 대해 생기는 에러 해결
이외에는 CASCADE 옵션 추가
=> [BE#224] manyToOne에 onDelete 옵션 추가

BE/src/app.module.ts, BE/src/mates/dto/response/mates.dto.ts, BE/src/mates/dto/response/status-message.dto.ts, BE/src/mates/mates.controller.ts, BE/src/mates/mates.entity.ts, BE/src/mates/mates.module.ts, BE/src/mates/mates.service.spec.ts, BE/src/mates/mates.service.ts, BE/src/users/entity/users.entity.ts
close #209 
- 친구 추가 기능
- 내 친구 목록 불러오기 기능
- 친구 삭제 기능
```ts
const user = await this.userRepository.findOne({
where: { id: user_id },
});
const following = await this.userRepository.findOne({
where: { nickname: following_nickname },
});
const mate = this.matesRepository.create({
follower_id: user,
following_id: following,
});
const result = await this.matesRepository.save(mate);
```
친구 추가하는 방법을 위 코드처럼 내 id로 user 객체 찾고, 등록 할 친구 닉네임으로 user 객체 찾고, 이 객체를 활용해서 mate 테이블에 넣어줬습니다. DB에 조회가 2번 발생하는데 다른 방법이 없는 것 같더라구요. 직접 SQL문을 넣으면 될 것 같긴 한데 일단 이렇게 처리해둔 상태입니다
=> [BE#209] 친구 조회 추가 삭제

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Application/DIContainer/AppDIContainer.swift, iOS/FlipMate/FlipMate/Application/DIContainer/CategoryDIContainer.swift, iOS/FlipMate/FlipMate/Application/DIContainer/LoginDIContainer.swift, iOS/FlipMate/FlipMate/Application/DIContainer/TabBarDIContainer.swift, iOS/FlipMate/FlipMate/Application/DIContainer/TimerSceneDIContainer.swift, iOS/FlipMate/FlipMate/Application/SceneDelegate.swift, iOS/FlipMate/FlipMate/Domain/UseCases/DefaultTimerFinishUseCase.swift, iOS/FlipMate/FlipMate/Domain/UseCases/DefaultTimerUseCase.swift, iOS/FlipMate/FlipMate/Domain/UseCases/Protocol/TimerFinishUseCase.swift, iOS/FlipMate/FlipMate/Domain/UseCases/Protocol/TimerUseCase.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/Flows/TimerFlowCoordinator.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerFinishViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/TimerFinishViewModel.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/TimerViewModel.swift, iOS/FlipMate/FlipMate/Presentation/Utils/CategoryManager/CategoryManager.swift, iOS/FlipMate/FlipMate/Presentation/Utils/Protocols/CategoryManagable.swift
closed #221 
- Face Down -> Face Up 될 때 저장 화면 UI 및 로직 구현
- CategoryManager 구현 (해당 Manager을 통해 여러 화면에서 카테고리 데이터 관리)
- 총 공부 시간 중복 누적 이슈 수정
- 다중 Cell 선택 이슈 수정
- 카테고리 cell 선택 후 공부 완료시 반영안되던 이슈 수정
https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/34525963-5f9d-4a7a-8d78-58921960c23c
기록 저장 화면에서 저장 여부 선택에 따라 타이머 화면으로 다시 dismiss될 때 데이터를 전달하기 위하여 TimerFlowCoordinator을 통해 데이터를 전달하였습니다.
기록 저장 화면에서 저장을 하게 되면 이전 화면으로 돌아오게 될 때 데이터를 전달해주기 위해 해당아래 코드와 같이 구현하였습니다.
``` swift
// TimerFlowCoordinator
private func didSaveStudyEndLog(studyEndLog: StudyEndLog) {
navigationController.dismiss(animated: true)
timerViewController?.appendStudyEndLog(studyEndLog: studyEndLog)
}
```
때문에 TimerFlowCoordinator가 timerViewController에 직접 접근하여 관련된 메소드를 실행시켜주고 있어서 은닉화에 어늣나는 것이 아닌가 싶기도 합니다........
결국에 …
=> [iOS] 공부 저장 화면 UI 및 로직 구현

iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewController/SignUpViewController.swift
close #139 
- 카메라 버튼 위치 및 모양 조정
- 프로필 사진을 탭 하여 사진첩에서 사진 선택하기 기능 구현
- 화면 터치 시 키보드 내리기 구현
| 동작 화면 |
| -- |
| <img src="https://github.com/boostcampwm2023/iOS06-FlipMate/assets/22342277/38b293eb-d79c-4708-9a36-6765164abfea" width=200> |
- 프로필 설정 및 닉네임 변경 뷰에서는 카메라 버튼을 통해 프로필 사진 변경 기능을 알린다.
- iOS 15 이상에서부터 적용되는 UIButton.Configuration 방식은 native한 이미지 크기 변경을 지원하지 않아서, 원본 이미지 크기가 사용하고자 하는 이미지보다 크다면 그것을 줄여서 사용하기 쉽지 않다.
- contentInset이나 layoutMargin을 주어도 원본 이미지 사이즈 이하로 변하지 않아서 카메라 이미지의 크기가 더 이상 작아지지 않는 것을 확인할 수 있었다.
- UIGraphicsImageRenderer를 사용해서 새로운 크기로 다시 이미지를 그리는 방법이 있었지만, UIImageView로 변경해서 사용하는 것이 간단하고 좋은 방법이라고 생각되었다.
- 왜냐하면 사진 변경을 위한 카메라 버튼은 highlighted 또는 터치 기능 등 버튼의 필수적인 기능을 가져야 할 필요는 없다고 생각했기 때문이다.
=> [iOS/#139] 회원가입 뷰 UI 개선

iOS/FlipMate/FlipMate/Data/Extension/UIColor++Extension.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/Flows/CategorySettingCoordinator.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/View/CategoryColorSelectView.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/View/CategoryListCollectionViewCell.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/View/CategorySettingFooterView.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/CategoryModifyViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/CategorySettingViewController.swift
close #217 
- 카테고리 수정 부분 present -> Push
- 액션 시트, Alert를 통한 삭제 및 수정 접근
- 카테고리 색상 호환
1. 기존 UIColor Extension 부분 특정 조건 시 8자리 String이 아니고 10자리 String이 나오는 오류가 종종 발견 되었습니다. 원인을 찾지는 못했지만 비트마스킹 중 오류로 예상됩니다. 따라서 로직 일부 수정하였습니다.
2. Action Sheet, Alert를 UIAlertController를 통해 구현하였습니다. 해당 부분은 뷰 전환으로 볼 수 없기 때문에 Coordinator 패턴 적용조차 고려하지 않았습니다. HIG의 언급되어 있는 삭제를 쉽게 할 수 없게 하라는 인용을 바탕으로 삭제 시도 시 2중 Alert (Action Sheet 선택 -> 경고 Alert)로 구현했습니다.
3. 카테고리 색상은 카테고리 Color String Property로 다루었습니다. 앞의 6자 String은 색상, 뒤의 2자 String은 alpha값을 0~255로 확장한 것입니다. color를 string으로 의존성을 관리하는 것이 조금 의아하긴 하지만 가장 좋은 방법이기도 한 것 같습니다.
++) 시뮬레이터 동작 중 발견한 버그 
1. DiffableDataSource & CollectionView 오류 
2. 카테고리 선택 후 타이머 실행 후 FaceUp 시 가끔 중단되지 않는 오류
3. Proximity Sensor 오류 (Found no UIEvent for backing event of type: 14; contextId: 0x0 발생 후 …
=> [iOS#217] 카테고리 색상 연결 및 삭제, 수정 화면 

BE/src/app.module.ts, BE/src/common/logging.interceptor.ts, BE/src/common/logging.middleware.ts
- Logger 요청부터 응답까지의 시간 측정
처음에는 아래와 같이 인터셉터에서 요청시 걸리는 시간과 응답시 걸리는 시간을 비교하도록 했다.
```ts
@Injectable()
export class LoggingInterceptor implements NestInterceptor {
private readonly logger = new Logger(LoggingInterceptor.name);
intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
const ctx = context.switchToHttp();
const request = ctx.getRequest();
const response = ctx.getResponse();
const { method, url, body } = request;
const now = Date.now();
this.logger.debug(`[Request] ${method} ${url} \n ${JSON.stringify(body)}`);
return next.handle().pipe(
tap((body) => {
const requestToResponse: `${number}ms` = `${Date.now() - now}ms`;
this.logger.debug(
`[Response] ${
response.statusCode
} ${requestToResponse} \n ${JSON.stringify(body)} \n`,
);
}),
);
}
}
```
하지만 아래의 그림을 보자
우리가 …
=> [BE#233] Logger 요청부터 응답까지의 시간 측정

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Common/Color/FlipMateColor.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/Protocol/FreindAddResultViewProtocol.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/View/FriendSearchResultView.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/View/MyNickNameView.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/View/NoResultView.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/FriendAddViewController.swift, iOS/FlipMate/FlipMate/Resources/Assets.xcassets/FilpMateColor/Gray3.colorset/Contents.json, iOS/FlipMate/FlipMate/Resources/Assets.xcassets/FilpMateColor/Gray5.colorset/Contents.json
closed #238 
- 친구 검색 TextField UI 구현
- 내 닉네임 화면 UI 구현
- 검색 결과 없을 떄 UI 구현
- 검색 결과 있을 떄 UI 구현
| 검색을 안한 상태 | 검색 결과가 없을 때 | 검색 결과가 있을 때 |
| -------- | -------- | -------- |
| ![simulator_screenshot_41F78F64-C1D3-4819-B409-74903C2EFCC7](https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/29afc05b-7389-43af-a66a-5c8f4621b076) | ![simulator_screenshot_98E1D8DD-7D6B-4228-BF2B-EBF52B817806](https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/83e176b4-bf7b-4e7a-a6c2-fcdd5f159a05) | ![simulator_screenshot_29FB52D5-60B0-4C82-B8A3-01143B11ADDA](https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/9f7a3de1-e9c9-466d-a641-1bad95624490)|
기획한 의도대로 UI가 보여지기 위해서는 친구 검색 TextField 아래에 각각의 상황에 맞는 View를 표시해야했습니다.
그래서 각 화면들을 프로토콜로 추상화를 하였고 메소드를 통해 해당 추상화된 뷰를 전달받아 뷰를 표시해주는 …
=> [iOS#238] 친구 추가하기 화면 UI 구현

BE/src/common/exception-filter/http-exception-filter.ts, BE/src/main.ts, BE/src/users/users.service.ts
close #259 
- Exception 로깅
- 프로필 변경시 닉네임 중복 예외
patch요청에 대해서 응답이 찍히지 않았다. 그 이유는 뭘까
Interceptor에서 요청과 응답에대해 찍어주고 있는데 예외가 나면 response를 캐치하지 못한다. 그래서 ExceptionFilter를 통해 예외시 로그를 따로 만들어주었다.
```ts
@Catch(HttpException)
export class HttpExceptionFilter implements ExceptionFilter {
private readonly logger = new Logger(LoggingInterceptor.name);
catch(exception: HttpException, host: ArgumentsHost) {
const ctx = host.switchToHttp();
const response = ctx.getResponse();
const request = ctx.getRequest();
const status = exception.getStatus();
const requestToResponse: `${number}ms` = request.now
? `${Date.now() - request.now}ms`
: `0ms`;
const errorResponse = {
statusCode: status,
message: exception?.message,
error: exception?.getResponse()['error'],
path: request.url,
timestamp: new …
```
=> [BE#259] Exception 로그, 프로필 변경시 닉네임 중복 예외

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate.xcodeproj/xcshareddata/xcschemes/FlipMateTests.xcscheme, iOS/FlipMate/FlipMate/Common/Logger/FlipMateLogger.swift, iOS/FlipMate/FlipMate/Data/Network/BaseComponents.swift, iOS/FlipMate/FlipMate/Data/Network/DataMapping/SocialScene/FriendFollowReqeustDTO.swift, iOS/FlipMate/FlipMate/Data/Network/DataMapping/SocialScene/UserProfileResposeDTO.swift, iOS/FlipMate/FlipMate/Data/Network/FriendEndpoints.swift, iOS/FlipMate/FlipMate/Data/Repositories/DefaultFriendRepository.swift, iOS/FlipMate/FlipMate/Domain/Entities/Friend.swift, iOS/FlipMate/FlipMate/Domain/Repositories/FriendRepository.swift, iOS/FlipMate/FlipMate/Domain/UseCases/DefaultFriendUseCase.swift, iOS/FlipMate/FlipMate/Domain/UseCases/Protocol/FriendUseCase.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/View/FriendSearchResultView.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/View/MyNickNameView.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/FriendAddViewController.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewModel/FriendAddViewModel.swift, iOS/FlipMate/FlipMateUseCaseTests/Mock/MockFriendRepository.swift, iOS/FlipMate/FlipMateUseCaseTests/SocialScene/FriendUseCaseTests.swift, iOS/FlipMate/FlipMateViewModelTests/Mock/MockFriendUseCase.swift, iOS/FlipMate/FlipMateViewModelTests/SocialScene/FriendAddViewModelTests.swift
closed #239 
- FriendUseCase 구현 (검색, 추가만 구현했는데 추후에 팔로우 취소, 차단까지 구현하시면 될 것 같습니다.)
- FriendRepository 구현
- FriendViewModel 구현
- FriendViewModel, FriendUseCase 테스트 코드 작성
아직 서버쪽에서 친구 추가요청 RepsonseDTO을 바뀐버전으로 안올려주셔서 친구 추가시에 에러가뜹니다!
https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/266e1fe5-896d-42b1-9372-eba5c32b9736
이번에 처음으로 VIewModel과 UseCase의 테스트 코드를 작성해보는 시간을 가졌는데요...
도대체 무엇을 테스트를 해야할지에 대해서 상당히 해맸습니다. 아직까지도 답을 못찾은 것 같습니다
ViewModel같은 경우에는 input과 output으로 추상화가 되어있다보니 
특정 input을 실행시켰을 때 이에 관련된 output이 정상적으로 나오는지에 대해서 테스트를 해줬고
UseCase는 Repository로부터 받는 응답 데이터를 entity로 변환이 되었는지 확인을 해주었습니다.
특히, ViewModel의 테스트 코드를 작성을 하면서 실제 다양한 케이스에 대해서 테스트를 해보고 싶었는데
input, output으로 추상화되어있다보니 테스트의 한계가 조금 있었던 것 같습니다.
=> [iOS] 친구 추가 비즈니스 로직 구현 및 테스트코드 작성

iOS/FlipMate/FlipMate/Application/AppFlowCoordinator.swift, iOS/FlipMate/FlipMate/Application/SceneDelegate.swift, iOS/FlipMate/FlipMate/Presentation/TabBar/Flows/TabBarFlowCoordinator.swift
close #272 
- keychain에서 token에 접근해, 토큰이 있다면 자동 로그인
* 탭바 뷰는 상위 네비게이션 컨트롤러로부터 접근한 window의 root view controller를 갈아끼워서 자신을 보여주고 있었다.
* 로그인 뷰를 통하지 않고, 앱 실행시 곧바로 탭바 뷰가 나오게 될 때는 window에 접근할 수 없어 까만 뷰가 나온다.
* 이를 해결하기 위해 navigation controller의 root view controlelr를 갈아끼워주는 방법이 아닌, navigation controller의 하위 뷰 컨트롤러로 탭바 뷰 컨트롤러를 삽입하는 방식을 선택했다.
=> [iOS#272] 자동로그인 구현

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Application/DIContainer/LoginDIContainer.swift, iOS/FlipMate/FlipMate/Domain/UseCases/DefaultSignUpUseCase.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/Flows/LoginFlowCoordinator.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewController/LoginViewController.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewModel/LoginViewModel.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewModel/SignUpViewModel.swift, iOS/FlipMate/FlipMate/Presentation/TabBar/Flows/TabBarFlowCoordinator.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/Flows/TimerFlowCoordinator.swift
close #275 
- 회원가입 화면 연결
- 중복 닉네임 검사 기능 고치기 완료
* Swift는 기본적으로 DispatchQueue.global, Task 등의 새로운 작업 흐름을 생성하는 코드를 만나지 않으면 main에서 sync하게 실행된다.
* 회원가입 완료 후 탭 바 뷰로 이동하는 로직은 뷰를 변경하기 때문에 메인 스레드에서 처리되어야 한다.
* 그런데 탭 바 뷰로 이동하는 로직을 실행하는 함수를 Task {} 안에 넣어 놓았었다.
* 이로 인해 메인 스레드가 아닌 다른 스레드에서 뷰의 변경이 일어나, 앱이 크래시가 나는 현상이 있었다.
* 처음에는 정확한 원인을 찾지 못하고 뷰를 이동시키는 모든 로직마다 DispatchQueue.main을 해 주었다.
* 그러나 Task 내부에서 실행한 최상위 함수가 원인임을 찾고, 해당 함수를 메인 스레드에서 실행하도록 변경해서 해결하였다.
=> [iOS#275] 회원가입 뷰 연결, 중복 닉네임 검사 로직 수정

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Application/DIContainer/SocialDIContainer.swift, iOS/FlipMate/FlipMate/Common/UserDefault/UserDefault.swift, iOS/FlipMate/FlipMate/Data/Network/DataMapping/SocialScene/FriendsResponseDTO.swift, iOS/FlipMate/FlipMate/Data/Network/DataMapping/SocialScene/UserProfileResposeDTO.swift, iOS/FlipMate/FlipMate/Data/Network/SignUpEndpoints.swift, iOS/FlipMate/FlipMate/Data/Network/SocialEndpoints.swift, iOS/FlipMate/FlipMate/Data/Repositories/DefaultFriendRepository.swift, iOS/FlipMate/FlipMate/Data/Repositories/DefaultSocialRepository.swift, iOS/FlipMate/FlipMate/Domain/Entities/Friend.swift, iOS/FlipMate/FlipMate/Domain/Repositories/FriendRepository.swift, iOS/FlipMate/FlipMate/Domain/Repositories/SocialRepository.swift, iOS/FlipMate/FlipMate/Domain/UseCases/DefaultFriendUseCase.swift, iOS/FlipMate/FlipMate/Domain/UseCases/DefaultSocialUseCase.swift, iOS/FlipMate/FlipMate/Domain/UseCases/Protocol/FriendUseCase.swift, iOS/FlipMate/FlipMate/Domain/UseCases/Protocol/SocialUseCase.swift, iOS/FlipMate/FlipMate/PersistenceService/UserInfoStorage.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewModel/SignUpViewModel.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/Model/FriendSearchItem.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/Model/FriendUser.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/View/FriendSearchResultView.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/View/FriendsCollectionViewCell.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/FriendAddViewController.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/SocialViewController.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewModel/FriendAddViewModel.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewModel/SocialViewModel.swift, iOS/FlipMate/FlipMate/Presentation/TabBar/Flows/TabBarFlowCoordinator.swift, iOS/FlipMate/FlipMateUseCaseTests/Mock/MockFriendRepository.swift, iOS/FlipMate/FlipMateViewModelTests/Mock/MockFriendUseCase.swift
closed #289 
- UserDefault구조체 propertyWrapper와 Publisher을 사용해 구현
- 회원가입 시 닉네임 UseDefault로 저장 (아직 로그인시에 저장은 구현을 못했슴다)
- UseDefault에 저장된 닉네임 필요한 화면에 바인딩
- 소셜 화면 viewDidAppear시 친구 상태 API 호출해서 화면에 바인딩
https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/17de5d2e-7a27-4642-886c-7c4dbf80cf58
UserDefault을 Combine을 통해 값을 바인딩 할 수 있는 방법이 없을까 생각하다가
문득 JK님의 마스터 클래스 강의에서 들었던 propertyWrapper을 사용하여 
UserDefault을 읽고 쓸때 get, set을 이용해 편하게 사용하는 방법이 떠올라
Publisher까지 추가하여 바인딩할 수 있도록 구현해봤습니다!
그러나,,, 해당 방식대로 구현하게 되면 Repository <-> Storage을 통해 읽고, 저장하는 방법이 아니라 
아마 추후에 레이어 분리하면서 수정하게 될 것 같습니다 ㅜ
=> [iOS#289] 소셜 화면 친구 상태 비즈니스 로직 구현

BE/src/study-logs/dto/response/daily-stat.dto.ts, BE/src/study-logs/study-logs.controller.ts, BE/src/study-logs/study-logs.service.ts
close #308
- 일간 통계 기능 구현
학습 시간과 카테고리 가져오는 건 기존 서비스 코드 사용했고, 랭킹? 구하는 건 쿼리로 쉬워서 바로 됐습니다
```sql
SELECT user_id, SUM(learning_time) AS total_time
FROM study_logs
WHERE date = ?
GROUP BY user_id
ORDER BY total_time DESC;
```
위 쿼리로 유저 별 학습 시간 찾은 다음에
```ts
const rank = result.findIndex((user) => user.user_id === userId) + 1;
const userCount = await this.usersRepository.count();
return (rank / userCount) * 100;
```
유저 아이디 인덱스를 이용해서 전체 유저 중 몇 등인지 계산하는 방식으로 했습니다
=> [BE#308] 일간 통계 기능 구현

BE/src/categories/categories.service.spec.ts, BE/src/categories/categories.service.ts, BE/src/mates/mates.service.spec.ts, BE/src/mates/mates.service.ts
close #314 
- 카테고리 최대 수 제한
- 친구 추가 최대 수 제한
```ts
const matesCount = await this.matesRepository.count({
where: { follower_id: user },
});
if (matesCount >= 10) {
throw new BadRequestException('친구는 최대 10명까지 추가할 수 있습니다.');
}
```
이런 식으로 해당 유저의 친구 수가 10명 이상이면 예외 처리 했습니다
카테고리도 같은 방식이에요
=> [BE#314] 카테고리, 친구 추가 최대 수 제한

iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/SocialViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/CategorySettingViewController.swift
close #312 
- 카테고리 뷰 네비게이션 타이틀 추가
- 소셜 뷰 탭 바 타이틀 제거
- 타이머 뷰에도 네비게이션 타이틀을 추가해 보았었는데, 시간 크기에 비해 타이틀 크기가 너무 작아 이상해서 빼버렸습니다.
- 소셜 뷰의 탭 바 타이틀이 없는 것이 낫다고 생각해 제외해 보았습니다.
- 아이폰 SE에서의 위치 문제 포함
=> [iOS#312] 카테고리 뷰 네비게이션 타이틀 추가

iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewController/SignUpViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/CategorySettingViewController.swift
close #313 
- 네비게이션 바 버튼 색상 .label로 변경
- 처음에는 모든 네비게이션 바에 동일한 설정을 주기 위해 커스텀 네비게이션 바 컨트롤러를 사용해볼까 고민했었다.
- 그러나 현재 Coordinator들에 가해져야 하는 변경점이 많을 것 같아서, 필요한 뷰 컨트롤러에서 직접적으로 값을 변경하고 있다.
=> [iOS/#313] 네비게이션 바 색상 통일 

iOS/FlipMate/FlipMate/Domain/UseCases/DefaultChartUseCase.swift, iOS/FlipMate/FlipMate/Presentation/ChartScene/View/DailyChartView.swift
close #344 
일일 통계 페이지 카테고리 색상 반영
SwiftUI 대단하군요, `chartforegroundstylescale` method로 손쉽게 범주의 색상을 변경할 수 있었습니다.
Category의 color string을 [Color] Array로 변환하는 함수 구현하여 반영했습니다.
=> [iOS/#344] 일일 통계 페이지 카테고리 색상 반영

iOS/FlipMate/FlipMate/Common/UserDefault/UserDefault.swift, iOS/FlipMate/FlipMate/Presentation/MyPageScene/ViewController/MyPageViewController.swift, iOS/FlipMate/FlipMate/Presentation/MyPageScene/ViewController/ProfileSettingsViewController.swift, iOS/FlipMate/FlipMate/Presentation/MyPageScene/ViewModel/MyPageViewModel.swift, iOS/FlipMate/FlipMate/Presentation/MyPageScene/ViewModel/ProfileSettingsViewModel.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewModel/SocialViewModel.swift
closed #349 
- 마이페이지에서 프로필 설정 시 소셜 화면에 반영
- 마이페이지 사용자 이미지 캐싱된 이미지 가져오도록 수정
- 프로필 수정 이미지 캐싱된 이미지 가져오도록 수정
https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/9734cfa5-dcc4-422f-ad83-9d290f49ff06
기존에 프로퍼티래퍼의 profjectValue을 통해서 UserDefault의 value을 바인딩해줬었는데
값이 바뀔때마다 새로운 profjectValue을 통해서 접근할 때마다 새로운 publisher 생기던 문제가 있어서
값이 바뀌는 경우에 새로운 값이 데이터 스트림에 보내지는게 아니라 새로운 값이 담긴 새로운 데이터 스트림이 생겼습니다.
그래서 내부에 subject을 생성해 해당 값을 읽을 때마다 subject을 통해 바인딩하도록 수정했습니다~~
``` swift
@propertyWrapper
struct UserDefault<T> {
private let key: String
private let defaultValue: T
private let subject = PassthroughSubject<T, Never>() // 추가
init(key: String, defaultValue: T) {
self.key = key
self.defaultValue = defaultValue
}
var wrappedValue: T {
get {
return UserDefaults.standard.object(forKey: key) as? T ?? …
```
=> [iOS#349] 마이페이지 닉네임, 프로필 사진 수정 로직 수정

iOS/FlipMate/FlipMate/Presentation/ChartScene/View/WeeklyChartView.swift, iOS/FlipMate/FlipMate/Presentation/ChartScene/ViewModel/ChartViewModel.swift
주간 학습 통계 페이지 로직 연결
디자인이 떠오르지 않아 그냥 조잡하게 만들었습니다...
다음에 추가할 UI 요소들 같이 얘기 하면 좋을 것 같습니다.
=> [iOS/#343] 주간 학습 통계 페이지 로직 연결

iOS/FlipMate/FlipMate/Data/Network/DataMapping/StatusResponseWithErrorDTO.swift, iOS/FlipMate/FlipMate/Data/Repositories/DefaultProfileSettingsRepository.swift, iOS/FlipMate/FlipMate/Domain/Repositories/ProfileSettingsRepository.swift, iOS/FlipMate/FlipMate/Domain/UseCases/DefaultProfileSettingsUseCase.swift, iOS/FlipMate/FlipMate/Domain/UseCases/Protocol/ProfileSettingsUseCase.swift, iOS/FlipMate/FlipMate/NetworkService/Provider.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewController/SignUpViewController.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewModel/SignUpViewModel.swift, iOS/FlipMate/FlipMate/Presentation/MyPageScene/ViewController/ProfileSettingsViewController.swift, iOS/FlipMate/FlipMate/Presentation/MyPageScene/ViewModel/ProfileSettingsViewModel.swift
close #321 
- 회원가입 및 프로필 설정 뷰 이미지 유해성 검사 결과 반영
- 닉네임 중복 검사를 유저 프로필 설정 API 요청 결과로 확인, 유저 사용성 개선
- 현재 로직은 올바른 값이 왔을 때만 Response DTO를 통해 전달받는다.
- 잘못된 요청에 대한 응답의 response body를 활용하려면?
- enum의 associated value 활용
- Error를 준수하는 APIError 열거형 타입을 만들고, StatusResponseWithErrorDTO 타입을 associated value로 가지는 errorResponse 케이스를 작성
```swift
enum APIError: Error {
case errorResponse(StatusResponseWithErrorDTO)
}
```
- 올바른 응답이 아닌 경우 StatusResponseWithErrorDTO로 디코딩, 그 값을 Error로 throw.
```swift
guard 200..<300 ~= response.statusCode else {
do {
if response.statusCode == 401 {
FMLogger.general.error("토큰이 만료되어 로그인 화면으로 이동합니다.")
signOutManager?.signOut()
}
let errorResult = try JSONDecoder().decode(StatusResponseWithErrorDTO.self, from: data)
FMLogger.general.error("에러 코드 : \(errorResult.statusCode)\n내용 : …
```
=> [iOS/#321] 이미지 유해성 검사 기능 구현

iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/TimerViewModel.swift
closed #303 
- 선택된 카테고리 다시 선택 시 해제되도록 수정
https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/aff0eb4f-12ba-4512-9134-e07c792715dc
shouldSelectedItemAt 메소드가 didSelectItemAt 메소드보다 일찍 호출된다는 것을 이용하여
해당 IndexPath의 Cell이 이미 선택되었는지 아닌지 isSelected값을 통해 이미 선택된 cell이라면 선택을 해제시켜주도록 구현했습니다 ~
=> [iOS#303] 선택된 카테고리 다시 선택 시 해제되도록 수정

iOS/FlipMate/FlipMate/Application/DIContainer/SocialDIContainer.swift, iOS/FlipMate/FlipMate/Application/DIContainer/TimerSceneDIContainer.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewModel/SocialViewModel.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/TimerViewModel.swift, iOS/FlipMate/FlipMate/Presentation/Utils/FriendStatusPollingManager/FriendStatusPollingManager.swift, iOS/FlipMate/FlipMate/Presentation/Utils/TimerManager/TimerManager.swift
closed #403 
- TimerManagerProtocol 구현
- ViewModel에서 TimerManager 주입받도록 수정
- ViewModel에서 Timer 상태 값 관리하던 것 TimerManager로 수정
이전에는 TimerManager가 필요한 ViewModel에서 생성해줘서 사용해줘서 ViewModel이 TimerManager에게 의존하는 관계였습니다.
그래서 TimerManager을 추상화하여 각각의 DI Container에서 주입받도록 수정하여 의존성을 관리해주었습니다.
또한 각각의 ViewModel에서도 Timer의 상태 값을 알기 위해서 TimerState을 가지고 있었는데 TimerManager의 TimerState을 통해서 관리하는 것으로 수정해서 불필요한 코드를 줄였습니다.
=> [iOS#403] TimerManager 추상화 및 의존성 관리

iOS/FlipMate/FlipMate/Presentation/ChartScene/ViewController/ChartViewController.swift, iOS/FlipMate/FlipMate/Presentation/MyPageScene/ViewController/MyPageViewController.swift, iOS/FlipMate/FlipMate/Resources/ko.lproj/Localizable.strings
closed #431 
- 타이머 종료 Alert Title 한국어 대응
- 통계화면 UISegmentedControl 영어일 때 너비 대응
- 마이페이지 닫기 버튼 다국어 대응
https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/337739da-27fd-4dcf-b620-cef8f38fe7db
=> [iOS#431] 다국어 지원 미흡한 부분 처리

iOS/FlipMate/FlipMate/Presentation/TimerScene/Model/CategorySettingSection.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/View/CategorySettingFooterView.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/CategorySettingViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/CategoryViewModel.swift, iOS/FlipMate/FlipMate/Presentation/Utils/CategoryManager/CategoryManager.swift, iOS/FlipMate/FlipMate/Presentation/Utils/Protocols/CategoryManagable.swift, iOS/FlipMate/FlipMate/Resources/en.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ja.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ko.lproj/Localizable.strings
closed #433 
- 카테고리가 10개인 경우에 카테고리 추가시 Alert 띄우기
- 카테고리가 많아질 경우 추가 버튼 짤리던 이슈 수정
https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/6567ef63-0a90-400e-bf68-82a390a99216
CompositionalLayout을 통해 구현을 해서 footerView의 contentInsets의 bottom값을 주면 footerView아래에 공백이 생길것으로 예상되었으나 bottom값을 준 만큼 footerView의 높이가 줄어드는 현상이 있었습니다..
따라서 FooterView 자체에 추가 버튼의 높이를 지정해주고 CompositionalLayout을 통해 footerView의 사이즈를 공백이 필요한 만큼 크기를 지정해서 해결하였습니다.
=> [iOS#433] 카테고리 10개인 경우 추가 버튼 처리

iOS/FlipMate/FlipMate/Presentation/TabBar/ViewController/TabBarViewController.swift
- 다크모드 일 때 스크롤시 탭바 색상 변하는 이슈 해결
https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/7f4ab1eb-67a7-46a1-b203-eaf873eb83af
스크롤시에 tabBar 뒤쪽에 어떠한 뷰가 있는 경우 불투명하게 backgroundColor가 바뀌는 문제가 있었습니다. 
iOS13이상부터 UITabBarAppearance을 통해 tabBar의 속성을 지정할 수 있는데 해당 appearance을 통해 backgroundColor을 지정해서 해결하였습ㄴ디ㅏ.
=> [iOS#436] 다크모드일 때 스크롤시 탭바 색상 변하는 이슈 해결

iOS/FlipMate/FlipMate/Domain/UseCases/DefaultChartUseCase.swift, iOS/FlipMate/FlipMate/Presentation/ChartScene/View/DailyChartView.swift, iOS/FlipMate/FlipMate/Resources/en.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ja.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ko.lproj/Localizable.strings
close #425
- 비율 계산하여 5% 미만의 카테고리 항목은 라벨을 제외하기로 하였습니다.
- 흑색 색상 위 흑색 라벨이 보이지 않는 것 해결하기 위해 흰색 외곽선있는 Text를 적용하였습니다.
- 비율 계산 과정 Naive하게 코드에 작성 중... Body에 추론할 타입이 너무 많다고 컴파일러가 맛가는 오류가 있었습니다... 별도 함수 만들어서 TypeCasting 줄여주니 해결되긴 했네요. 당황했습니다.
=> [iOS/#425] 차트 페이지 UI 개선

iOS/FlipMate/FlipMate/NetworkService/Provider.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewController/SignUpViewController.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewModel/SignUpViewModel.swift, iOS/FlipMate/FlipMate/Presentation/MyPageScene/ViewController/ProfileSettingsViewController.swift, iOS/FlipMate/FlipMate/Presentation/MyPageScene/ViewModel/ProfileSettingsViewModel.swift, iOS/FlipMate/FlipMate/Resources/en.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ja.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ko.lproj/Localizable.strings
close #423 
close #424 
- 이미지 업로드 중 에러 발생 시 alert 발생
- 이미지 압축 퀄리티 낮춰서 용량 줄이기
- 이미지 회전되어서 업로드되는 에러 수정
- PHPicker로 가져올 수 있는 .image 종류인 live photo, 일반 이미지, 인물사진 등등 모두 테스트해 보았다.
- 특별히 업로드되지 않는 이미지는 없었다. (.gif도 업로드 되었다)
- 문제는 매우 큰 용량의 이미지 (RAW 파일) 및 internal server error
- 해당 에러들이 있을 때 사용자에게 알려주기 위해서 alert를 구현
- Flie too large 에러 출현 빈도를 낮추기 위해 compression quality 1.0 -> 0.6으로 변경
- 이미지 정보에 함께 기록되는 메타 정보(EXIF)에 이미지 방향이 기록되어 있다. [공식문서] (https://developer.apple.com/documentation/uikit/uiimage/1624141-imageorientation)
- 디버깅 결과 사용자 이미지의 회전 메타 정보가 함께 서버로 올라가고, 서버에서 해당 메타 정보를 이용해서 이미지를 회전시켜서 돌려보내주고 있었다.
- 이를 방지하기 위해 이미지의 회전 메타 정보를 지운 후 서버로 전송해 주었다.
```swift
private func removedOrientationImage(_ image: UIImage) -> UIImage {
guard image.imageOrientation != .up else { return image } …
```
=> [iOS#423] 이미지 업로드 시 에러 처리

iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewController/SignUpViewController.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewModel/SignUpViewModel.swift, iOS/FlipMate/FlipMate/Presentation/MyPageScene/ViewController/ProfileSettingsViewController.swift, iOS/FlipMate/FlipMate/Presentation/Utils/NickNameValidator/NickNameValidator.swift, iOS/FlipMate/FlipMate/Resources/en.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ja.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ko.lproj/Localizable.strings
close #421 
- 프로필 수정 및 회원가입 화면에서 이모티콘 입력 제한
- 카테고리 기능에서는 이모티콘을 사용하고 싶어하는 사용자도 있을 것으로 생각
- 닉네임과는 다르게 사용해도 무방
- DB의 설정을 변경해서 사용할 수 있도록 할 예정
- unicodeScalar 활용
- [참고](https://betterprogramming.pub/understanding-swift-strings-characters-and-scalars-a4b82f2d8fde)
=> [iOS#421] 프로필 설정에서 이모티콘 입력 제한하기

BE/src/admin/admin.controller.ts, BE/src/auth/auth.controller.ts, BE/src/auth/auth.service.ts, BE/src/auth/guard/bearer-token.guard.ts, BE/src/common/config/typeorm.config.ts, BE/src/users/entity/users.entity.ts, BE/src/users/users.service.ts
close #449 
- 애플 로그인 구현
- 공개키를 이용해서 JWT토큰을 검증하는 과정
- 'https://appleid.apple.com/auth' 에 요청하면 공개 키를 받을 수 있습니다
- 공개키를 받아서 JWT 헤더의 kid 값과 같은 값을 가진 공개 키를 활용해서 검증합니다.
- 받은 jwt.verify()에 파라미터로 들어가는 key 값은 pem 형식인데 우리가 받은 공개키는 pem이 아니라서 해당 형식으로 바꿔줘야 합니다.
```ts
const JWK = crypto.createPublicKey({
format: 'jwk',
key: {
kty,
n,
e,
},
});
JWK.export({
type: 'pkcs1',
format: 'pem',
});
```
위 코드를 통해서 애플로부터 받은 공개키를 jwk 형태로 바꿔주고, 이를 다시 pem으로 바꿀 수 있습니다. 이 값을 공개키로 활용해 jwt를 검증할 수 있습니다 !
+ 이모지 config 한줄이면 수정 되서 추가했어요 DB 안날려도 되는 것 같습니다
=> [BE#449] 애플 로그인 구현

BE/src/auth/auth.controller.ts, BE/src/mates/mates.controller.ts, BE/src/mates/mates.service.ts, BE/src/users/entity/users.entity.ts, BE/src/users/users.service.ts
close #439
- user 테이블에 timezone 생성
- getMates 메서드에서 요청 온 시각을 각 유저 타임존으로 바꿔 날짜 추출 후 학습 기록 조회하도록 수정
```ts
async getMates(
user_id: number,
date: string,
now = new Date(),
): Promise<object[]> {
const userTimezone = await this.userRepository.findOne({
where: { id: user_id },
});
const nowUserTime = moment(now).utcOffset(userTimezone.timezone).format();
const studyTimeByFollowing = await this.userRepository.query(
`
SELECT u.id, u.nickname, u.image_url, COALESCE(SUM(s.learning_time), 0) AS total_time
FROM users_model u
LEFT JOIN mates m ON m.following_id = u.id
LEFT JOIN study_logs s ON s.user_id = u.id AND s.date = DATE(CONVERT_TZ(?, ?, u.timezone))
WHERE m.follower_id = ? 
GROUP BY u.id
ORDER BY total_time DESC
`,
[nowUserTime, userTimezone.timezone, user_id],
);
```
현재 친구들의 날짜를 알아야 하니까 결국 …
=> [BE#439] fix: 소셜 화면 타임존 이슈 해결

BE/src/auth/google.strategy.ts, BE/src/mates/mates.controller.ts, BE/src/mates/mates.service.ts
auth_type 문제는 브라우저로그인시에만 발생해서 이렇게 넣어주어 해결
timezone 추가로 받아서 이를 띄어쓰기 여부를 통해 파악하여 해결
=> [BE#453] auth type null문제, GET요청에 body를 query로

iOS/FlipMate/FlipMate/Presentation/ChartScene/View/CustomCalenderView.swift
close #434 
- DatePicker 오늘 날짜로 스크롤 되게 수정
막상 완성해보니까 별 거 아니었는데, 구현 중 SwiftUI에서 View Life Cycle과 관련해서 자꾸 버그가 있었습니다.
각 날짜 마다 index를 매겨서 (1일 - 0, 2일 - 1, 3일 - 2, ... , 31일 - 30), 오늘 날짜 - 1로 강제 스크롤하게 하였습니다.
++
실수로 main에 푸쉬해서 revert 하였습니다 !!
=> [iOS/#434] DatePicker 오늘 날짜로 스크롤 되게 수정

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Application/DIContainer/TabBarDIContainer.swift, iOS/FlipMate/FlipMate/Application/DIContainer/TimerSceneDIContainer.swift, iOS/FlipMate/FlipMate/Data/Network/BaseComponents.swift, iOS/FlipMate/FlipMate/Data/Network/DataMapping/TimerScene/TimeZoneRequestDTO.swift, iOS/FlipMate/FlipMate/Data/Network/SignUpEndpoints.swift, iOS/FlipMate/FlipMate/Data/Network/SocialEndpoints.swift, iOS/FlipMate/FlipMate/Data/Network/UserInfoEndpoints.swift, iOS/FlipMate/FlipMate/Data/Repositories/DefaultTimerRepository.swift, iOS/FlipMate/FlipMate/Data/Repositories/DefaultUserInfoRepository.swift, iOS/FlipMate/FlipMate/Domain/Repositories/UserInfoRepository.swift, iOS/FlipMate/FlipMate/Domain/UseCases/DefaultTimeZoneUseCase.swift, iOS/FlipMate/FlipMate/Domain/UseCases/Protocol/TimeZoneUseCase.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/SocialViewController.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewModel/SocialViewModel.swift, iOS/FlipMate/FlipMate/Presentation/TabBar/Flows/TabBarFlowCoordinator.swift, iOS/FlipMate/FlipMate/Presentation/TabBar/ViewController/TabBarViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/TimerViewModel.swift, iOS/FlipMate/FlipMate/Presentation/Utils/Extensions/Date++Extension.swift, iOS/FlipMate/FlipMate/Presentation/Utils/FriendStatusPollingManager/FriendStatusPollingManager.swift, iOS/FlipMate/FlipMate/Resources/en.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ja.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ko.lproj/Localizable.strings
closed #447 
- 사용자 TimeZone이 바뀐경우 화면 새로고침되도록 구현
- 사용자간 TimeZone에 대응할 수 있도록 TimeZone patch API 요청
https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/9124b26d-f6d9-4409-8259-24dab194dc4d
hi의 날짜가 바뀐다하더라도 hello의 오늘 공부 시간은 변하지 않음
사용자의 TimeZone이 변경되었을 경우 기존에는 이전 데이터가 그대로 보여주고 있었다. 여기서 문제가 발생했는데 만약 사용자가 마지막으로 앱을 사용했던 날짜와 TimeZone이 바뀌고 난 뒤 앱을 사용했던 날짜가 다르게 된다면 동기화문제가 발생하게 된다.
마지막으로 12일의 데이터를 보고 있던 사용자는 TimeZone이 바뀌고 13일이 되었음에도 불구하고 12일 데이터를 보는 상황이 생기게 된다. 그래서 사용자의 디바이스 TimeZone이 바뀌었을 경우를 감지하여 바뀔 때마다 화면을 새로고침해줘서 데이터 동기화를 해결했다.
다행히 `NSSystemTimeZoneDidChange` SystemNotification이 존재하여 비교적 간단하게 TimeZone이 바뀐지 여부를 확인할 수 있었고
TabBarController에서 TimeZoneDidChange Notification을 등록해줘서 감지를 하게 되면 TabBarFlowCoordinator에서 TabBarController의 delegate을 채택하여 감지가될 때마다 tabBarController을 다시 화면에 띄워주도록 …
=> [iOS#447] 사용자 및 사용자간 TimeZone 대응

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Data/Network/DataMapping/SocialScene/UserProfileResposeDTO.swift, iOS/FlipMate/FlipMate/Data/Network/FriendEndpoints.swift, iOS/FlipMate/FlipMate/Data/Repositories/DefaultFriendRepository.swift, iOS/FlipMate/FlipMate/Domain/Entities/FriendSearchResult.swift, iOS/FlipMate/FlipMate/Domain/Repositories/FriendRepository.swift, iOS/FlipMate/FlipMate/Domain/UseCases/DefaultFriendUseCase.swift, iOS/FlipMate/FlipMate/Domain/UseCases/Protocol/FriendUseCase.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/Model/FriendSearchItem.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/View/FriendSearchResultView.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/FriendAddViewController.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewModel/FriendAddViewModel.swift, iOS/FlipMate/FlipMate/Resources/en.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ja.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ko.lproj/Localizable.strings
closed #451 
- 친구 검색 시 이미 친구인 친구와, 나 자신을 검색했을 떄 검색 결과에 표시되도록 수정
- 기존의 Toast는 친구 추가시 네트워크 에러 발생시 다시 시도 메시지 띄우는걸로 수정
https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/820eb327-a599-4aa1-97a7-1bea3dcf6f84
바뀐 요구사항과 서버 API을 토대로 20000, 20001, 20002 상태 코드에 따라 검색 결과를 매핑할 수 있게 FriendSearchStatus 열거형을 만들어 Entity에 포함되게 수정하였습니다. 해당 Status에 따라 검색 결과 View에서 친구 추가 버튼 또는 설명 label이 뜨도록 구현했습니다.
기존에 구현해뒀던 toast 메시지는 지우지 않고 혹여나 친구 추가시에 에러가 발생한 경우 토스트 메시지로 다시 시도해달라고 사용자에게 보여주는 것으로 수정했습니다!
=> [iOS#451] 친구 검색 로직 수정

iOS/FlipMate/FlipMate/Presentation/TimerScene/Flows/CategorySettingCoordinator.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/CategoryModifyViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerFinishViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/CategoryModifyViewModel.swift, iOS/FlipMate/FlipMate/Resources/en.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ja.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ko.lproj/Localizable.strings
close #464 
1. 카테고리 1~10자
2. 카테고리 이름 중복시
기존 NickNameValidator를 사용하려면 NameValidatorable 같은 protocol로 추상화 하여야 했는데, 귀찮아서 그냥 viewModel에서 로직 체크하도록 하였습니다.
Alert 띄우도록 했는데, 어색하면 추후 수정하는게 좋을 것 같습니다.
(닉네임처럼 작성 중 경고를 띄울 지 ...)
=> [iOS/#464] 카테고리 추가/변경 규칙 설정

iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerFinishViewController.swift
close #476 
- Timer-Finish View에서 [예] 버튼 다중 터치시 누적되어 저장되는 버그 수정
직관적으로 Button의 isEnabled Property를 다루는 방법으로 수정했습니다.
다만 버튼과 관련하여 해당 버그와 같은 경우가 많을 것 같은데, 그럴때마다 위 방법으로 하는 것이 맞는지도 조금 의문이 듭니다 -
만약 모든 버튼이 일회성 터치만 요구한다면, UIButton Extension으로 뺄 수 있을 것 같기도 하네요
=> [iOS/#476] 버튼 다중 터치 버그 수정

BE/src/mates/mates.controller.ts, BE/src/mates/mates.entity.ts, BE/src/mates/mates.service.spec.ts, BE/src/mates/mates.service.ts
close#487
- 친구 고정 기능 구현
- 친구 목록 불러올 때 고정된 것 우선적으로 받아오기
- entity에 fixation 열 추가 (true면 고정, false면 고정x)
- Body로 친구id, 고정/해제 여부 받아서 수정하기
=> [BE#487] 친구 고정 기능

iOS/FlipMate/FlipMate/Presentation/SocialScene/View/SocialUserInfoHeaderView.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/SocialViewController.swift, iOS/FlipMate/FlipMate/Resources/en.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ja.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ko.lproj/Localizable.strings
close #489 
사실 팔로잉 확인 기능 구현 태스크 중 하나의 과정인데, PR 양이 방대해질 것 같아 해당 Task를 조금씩 쪼개기로 하였습니다.
1. 현재 UI도 다소 어색한 부분이 있습니다. 향후 계획은 팔로워 목록을 확인하기 위해서는 `팔로워` 라벨을 터치하게끔 하고 싶은데, 현재 디자인상 팔로잉 목록은 CollectionView로 자동으로 표현되어 있는 상황입니다. 팔로잉 목록도 `팔로잉` 라벨을 터치했을 때 보여주게 하면 하단이 텅 비어있어 대대적인 교체가 필요할 것 같습니다.
2. 팔로잉, 팔로워 라벨을 스택뷰로 구현하였는데, 사실 같은 모양이라 상위 view로 묶어 구현하였으면 편리하였을 것 같기도 한데, 귀찮기도 하고 해당 UI가 단 2개(소셜 탭의 팔로잉, 팔로워)만 사용되어 HeaderView에 중복된 코드가 작성된 감이 있습니다.
3. 또한 소셜과 소셜 상세창의 UX는 비슷한데 UI는 조금 달라 친구를 탭하여 상세 화면 진입시 다소 이질감이 느껴집니다.
=> [iOS/#489] 팔로워 확인을 위한 Social tap UI - HeaderView 변경

BE/src/heartbeat/heartbeat.module.ts, BE/src/heartbeat/heartbeat.service.ts, BE/src/mates/mates.service.ts, BE/src/study-logs/dto/request/create-study-logs.dto.ts, BE/src/study-logs/study-logs.entity.ts, BE/src/study-logs/study-logs.service.ts, BE/src/users/entity/users.entity.ts
close #491
- hearbeat 30초동안 안오는 경우 자동으로 학습 기록 저장
- 친구 불러올 때 1. 고정 여부 2. 학습 중 여부 3. 학습 시간 순으로 우선적으로 로드
- 학습 기록 테이블에 정상 종료 되었는지에 대한 칼럼 추가
- 유저 테이블에 학습 중인지에 대한 칼럼 추가
- 학습 시작 시 redis에 해당 학습 카테고리 저장
- 30초동안 heartbeat 없을 때 redis에 저장된 데이터를 이용해 db에 데이터 저장 후 redis 값 삭제
=> [BE#491] heartbeat가 없는 경우 학습 기록 자동 저장

BE/src/mates/mates.controller.ts, BE/src/mates/mates.service.spec.ts, BE/src/mates/mates.service.ts
close #501 
- 친구 목록 페이지네이션 
- 10명 이상이어도 친구 추가 가능
- 한 번에 9명씩 나오도록
- 요청 uri `/datetime/timezone` -> `/datetime/timezone/page` 변동
- page는 0부터 1씩 증가하도록 넣어주면 정상 동작
=> [BE#501] 친구 목록 페이지네이션 추가

BE/src/auth/auth.controller.ts, BE/src/auth/dto/response/get-info.dto.ts, BE/src/auth/dto/response/update-info.dto.ts, BE/src/main.ts, BE/src/mates/dto/request/pagination-query.dto.ts, BE/src/mates/dto/response/follower-info.dto.ts, BE/src/mates/dto/response/mates-info.dto.ts, BE/src/mates/dto/response/mates.dto.ts, BE/src/mates/mates.controller.ts, BE/src/mates/mates.service.spec.ts, BE/src/mates/mates.service.ts, BE/src/study-logs/study-logs.controller.ts, BE/src/users/dto/response/nickname-validation.dto.ts, BE/src/users/dto/response/user-profile.dto.ts, BE/src/users/users.controller.ts, BE/src/users/users.service.ts
close #505 
- test코드에 이전에 추가한 is_blocked 추가되지 않아 추가
- auth, user 관련 잘못된 스웨거 문서 작성 (response dto 작성)
- GET /mates/followers 요청에 is_followed 추가
- 커서기반 페이지네이션
query를 통해 받으면 무조건 string이라 매번 number로 변환 시켜주는 것에 대해 회의감을 느껴 pagination DTO에 class-transformer에서 제공해주는 데코레이터를 활용했습니다.
클라이언트로부터 요청을 받으면 이 dto를 검증하는 과정에서 변환도 같이 해주는 것인데, 이를 위해 main함수에 useGlobalPipes에 관련 설정을 추가해야 했습니다.
기존 쿼리에 limit와 offset을 추가하여 했습니다. 그런데 지금와서 보니 실수한 것 같습니다...! 이건 페이지기반 페이지네이션이네요.. 일단 PR 올려두고 수정하겠습니다ㅠ
=> [BE#505] 팔로우 조회 커서기반 pagination

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Application/DIContainer/ChartDIContainer.swift, iOS/FlipMate/FlipMate/Domain/UseCases/Chart/DefaultFetchWeeklyChartUseCase.swift, iOS/FlipMate/FlipMate/Domain/UseCases/Protocol/Chart/FetchWeeklyChartUseCase.swift, iOS/FlipMate/FlipMate/Presentation/ChartScene/View/BarChartView.swift, iOS/FlipMate/FlipMate/Presentation/ChartScene/ViewController/ChartViewController.swift, iOS/FlipMate/FlipMate/Presentation/ChartScene/ViewModel/ChartViewModel.swift
closed #508 
- CGContext을 통한 막대 그래프 구현
- 주간 학습 기록과 막대 그래프 연동
https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/d17bec72-e308-4de6-af44-8378240bf999
barChartView의 frame의 height을 기준으로 데이터와의 비율을 통해서 막대를 그리다보니 값이 작은 데이터가 들어간 경우에는 전체적으로 막대들의 높이가 작게 그려지는 문제가 있었습니다.
해당 문제를 해결하기 위해서 barChartView의 frame의 height을 기준으로 잡지 않고 전달받은 데이터 배열 중에 가장 큰 값을 기준으로 나머지 데이터들의 비율을 구해서 막대의 높이를 설정하는 것으로 수정해 문제를 해결했습니다!
``` swift
for dailyData in dailyDatas {
let dataPoint = CGFloat(dailyData.studyTime)
let barHeight = (dataPoint / CGFloat(maxPoint)) * frame.height
let yPosition = frame.height - barHeight
let barRect = CGRect(x: xPosition, y: yPosition, width: barWidth, height: barHeight)
context.fill(barRect)
addTextLayer(position: CGPoint(x: xPosition, y: yPosition), text: "\(dailyData.studyTime)", …
```
=> [iOS#508] 주간 막대 그래프  SwiftUI -> UIKit 리팩토링
