boostcampwm2023/iOS06-FlipMate

iOS/.gitignore
closed #7 
- gitignore 파일 생성 후 설정
- xcodeproj 파일을 .gitignore에 등록하면 문제가 발생할 수 있어서 잠시 보류했습니다.
=> [iOS#7] iOS 프로젝트 .gitignore 설정

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate.xcodeproj/project.xcworkspace/contents.xcworkspacedata, iOS/FlipMate/FlipMate.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, iOS/FlipMate/FlipMate/Application/AppDelegate.swift, iOS/FlipMate/FlipMate/Application/SceneDelegate.swift, iOS/FlipMate/FlipMate/Presentation/Splash/ViewController.swift, iOS/FlipMate/FlipMate/Resources/Assets.xcassets/AccentColor.colorset/Contents.json, iOS/FlipMate/FlipMate/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json, iOS/FlipMate/FlipMate/Resources/Assets.xcassets/Contents.json, iOS/FlipMate/FlipMate/Resources/Base.lproj/LaunchScreen.storyboard, iOS/FlipMate/FlipMate/Resources/Info.plist, iOS/FlipMate/FlipMateTests/FlipMateTests.swift, iOS/FlipMate/FlipMateUITests/FlipMateUITests.swift, iOS/FlipMate/FlipMateUITests/FlipMateUITestsLaunchTests.swift
close #10 
- 클린 아키텍처 + MVVM 구조를 사용한 폴더링 적용, iOS 최소 지원 버전 설정
- 어떤 아키텍처를 사용해서 프로젝트를 진행할 지 고민해 보았습니다.
- 뷰모델의 재사용 및 뷰의 분리로 인한 확장성이라는 장점을 활용하기 위해 MVVM 아키텍처를 사용하기로 하였습니다.
- 가독성과 재사용성, 테스트를 용이하게 할 수 있도록 클린 아키텍처 구조를 참고해 폴더링을 진행하였습니다.
=> [iOS#10] iOS 프로젝트 초기 설정

BE/.eslintrc.js, BE/.gitignore, BE/.prettierrc, BE/nest-cli.json, BE/package-lock.json, BE/package.json, BE/src/app.controller.spec.ts, BE/src/app.controller.ts, BE/src/app.module.ts, BE/src/app.service.ts, BE/src/main.ts, BE/test/app.e2e-spec.ts, BE/test/jest-e2e.json, BE/tsconfig.build.json, BE/tsconfig.json
close #8 
Nest JS boilerplate를 통해 초기 개발환경을 구성 했다.
npm을 할까 yarn을 할까 pnpm을 할까 고민했고, 우선 익숙한 npm을 사용해보고 추후에 성능 비교를 해보기로 했다.
=> [BE#8] NestJS 초기 개발환경 구성

iOS/.gitignore, iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate.xcworkspace/contents.xcworkspacedata, iOS/FlipMate/FlipMate.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, iOS/FlipMate/Podfile, iOS/FlipMate/Podfile.lock
이전 커밋의 plist 디렉토리 이동으로 인해 빌드 오류가 발생하여 타겟 변경
++ Pods 폴더는 push 되지 않기 때문에 첫번째 pull 시 각자 터미널에서 `pod install` 해주시면 됩니다 ^^
=> [iOS#14] SwiftLint 설치

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Application/SceneDelegate.swift, iOS/FlipMate/FlipMate/Presentation/TabBarViewController.swift
close #31 
Custom TabBarController 구현하였습니다.
https://github.com/boostcampwm2023/iOS06-FlipMate/assets/138603822/9591711b-a41c-4549-9d01-e847534339e1
https://github.com/boostcampwm2023/iOS06-FlipMate/assets/138603822/f1e941ce-6fc1-4a44-8984-498b71a2f9a7
가운데의 타이머를 버튼으로 따로 할 지 아니면 탭을 커스텀할 지 고민하다가 버튼으로 하면 구조상 탭은 2개밖에 없기 때문에 어색하다고
생각하여 탭 자체를 커스텀하였습니다.
버튼이 아니고 탭 자체를 커스텀하다보니 AutoLayout을 잡는 데에 어려움이 있어 원의 크기는 따로 수식을 지정하였습니다.
+ 항상 timer가 tinted 효과가 적용되는 데에 원인을 찾을 수 없어 mode를 .dimmed로 정해두었습니다.
++ 영상과 달리 이후에 탭 자체의 배경색이 흰색으로 고정되게끔 하였습니다.
=> [iOS#31] Custom Tab Bar 구현

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Presentation/ChartScene/ViewController/ChartViewController.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewController/LoginViewController.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/SocialViewController.swift
closed #45 
- 비로그인 버튼 클릭시 타이머 화면으로 이동 구현
https://github.com/boostcampwm2023/iOS06-FlipMate/assets/48830320/eec4095d-e8e4-4ead-95e4-d1be3b63ec7b
=> [iOS#45] 비로그인 버튼 클릭시 화면 전환 구현

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Data/Extension/UIView++Extension.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewController/LoginViewController.swift, iOS/FlipMate/FlipMate/Presentation/TabBarViewController.swift
closed #54 
- UIView의 extension을 통해 shadow설정하는 메소드 구현
UIView을 상속한 클래스에서 setShadow() 메소드를 실행하면 그림자가 설정됩니다 -> `button.setShadow() `
=> [iOS#54] 그림자 설정 메소드 구현

iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift
- categoryManageButton 누락 부분 추가
=> [iOS#fix] categoryManageButton 누락 부분 추가

BE/package-lock.json, BE/package.json, BE/src/app.module.ts, BE/src/study-logs/study-logs.controller.spec.ts, BE/src/study-logs/study-logs.controller.ts, BE/src/study-logs/study-logs.entity.ts, BE/src/study-logs/study-logs.module.ts, BE/src/study-logs/study-logs.service.spec.ts, BE/src/study-logs/study-logs.service.ts
close #63 
- TypeORM을 쓸지 Prisma를 쓸지: 당장 참고자료가 많은 TypeORM을 우선적으로 경험해보고 prisma 도입 나중에 고민해보기
- 고민보다는 NestJS 구조와 TypeORM의 구조 및 사용방법에 대해 공부를 많이 했다.
=> [BE#63] TypeORM으로 DB 연동, DB 생성

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Presentation/TabBarViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift, iOS/FlipMate/FlipMate/Presentation/Utils/FeedbackManager/FeedbackManager.swift
closed #61 
- faceDown 상태에서만 근접거리 센서 활성화하여 화면이 꺼지도록 구현
- 디바이스 faceDown 상태 & 근접거리 센서 활성화시에 햅틱 피드백 구현
- 추후에 다른 기능에도 햅틱 피드백을 적용하기 위해 햅틱 피드백을 관리하는 FeedbackManager 객체를 생성하여 구현하였습니다.
- 추상화된 객체가 아닌 구현되어있는 실제 객체를 주입받는 것이라 init에서 주입받지 않고 내부에서 가지고 있어도 될 것 같다고 느껴져서 해당 부분에 대해서 의논해보면 좋을 것 같습니다 ~!
=> [iOS#61] 디바이스 face down시 햅틱 & 화면 끄기 구현

BE/package-lock.json, BE/package.json, BE/src/main.ts, BE/src/study-logs/study-logs.controller.ts, BE/src/study-logs/study-logs.entity.ts, BE/src/study-logs/study-logs.service.ts
close #22 
- 타이머 화면 컨트롤러 작성
- 타이머 화면에서 사용할 API 문서화 (Swagger)
=> [BE#22] 타이머 화면 컨트롤러 작성 및 API문서화

BE/src/app.module.ts, BE/src/categories/categories.controller.spec.ts, BE/src/categories/categories.controller.ts, BE/src/categories/categories.entity.ts, BE/src/categories/categories.module.ts, BE/src/categories/categories.service.spec.ts, BE/src/categories/categories.service.ts
close #23 
categories 컨트롤러 작성 및 API문서화
=> [BE#23]categories 컨트롤러 작성 및 API문서화

BE/src/app.module.ts, BE/src/users/users.controller.spec.ts, BE/src/users/users.controller.ts, BE/src/users/users.entity.ts, BE/src/users/users.module.ts
close #68 
- User 컨트롤러 작성
- API 문서화
=> [BE#68] users 컨트롤러 작성 및 API 문서화

BE/src/study-logs/study-logs.controller.ts, BE/src/study-logs/study-logs.module.ts, BE/src/study-logs/study-logs.service.ts
close #70 
모듈들이 DB 테이블과 대응해야 한다고 생각해서 study-logs 하위에 stats 컨트롤러 추가 했습니다. 어떻게 생각하시나요!?
=> [BE#70] stats 컨트롤러 작성 및 API문서화

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj
지난 merge 중 conflict 발생한 pbxproj 해결 중 누락 된 부분이 있어 추가해서 다시 올립니다.
=> [iOS#85] pbxproj 누락 해결

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/FaceDown.ahap, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift, iOS/FlipMate/FlipMate/Presentation/Utils/FeedbackManager/FeedbackManager.swift
- FeedbackManager가 CoreHaptics를 사용하도록 변경
- 조금 더 명료한 햅틱 진동이 느껴지도록 개선
- 필요한 만큼의 커스텀 가능
- 휴대폰을 뒤집을 경우 어떤 진동이 어울릴지 커스텀해보는 것도 좋아 보입니다.
=> [iOS#79] CoreHaptics 프레임워크를 사용한 햅틱 피드백 개선

iOS/FlipMate/.swiftlint.yml, iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj
- 불필요한 룰 disable
- 필요한 룰 수정해서 사용
- trailing_whitespace 룰은 불필요하다고 판단되어 disable 하였습니다.
- 최대 줄 길이, 변수명 길이 등 같이 의논해서 정하면 좋을 룰들이 있었습니다.
=> [iOS#83] SwiftLint 룰 변경

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Domain/UseCases/DefaultTimerUseCase.swift, iOS/FlipMate/FlipMate/Domain/UseCases/Protocol/TimerUseCase.swift, iOS/FlipMate/FlipMate/Presentation/TabBarViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/TimerViewModel.swift, iOS/FlipMate/FlipMate/Presentation/Utils/Protocols/Int++Extension.swift, iOS/FlipMate/FlipMate/Presentation/Utils/TimerManager/TimerManager.swift
closed #28
- 타이머 Usecase 구현
- 타이머 관리 TimerManager 구현
- Face Up 상태에서 타이머 시작 로직 구현
- Face Up 아닌 상태에서 타이머 일시 중지 로직 구현
[타이머 구현고민 과정](https://yeim.notion.site/Timer-26afd5eec87b431fb29347cf4f223351)
=> [iOS#28] 타이머 로직 구현

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Common/Constant/FlipMateConstant.swift, iOS/FlipMate/FlipMate/Common/Logger/FlipMateLogger.swift, iOS/FlipMate/FlipMate/Domain/UseCases/DefaultTimerUseCase.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/TimerViewModel.swift, iOS/FlipMate/FlipMate/Presentation/Utils/FeedbackManager/FeedbackManager.swift, iOS/FlipMate/FlipMate/Presentation/Utils/TimerManager/TimerManager.swift
- FMLogger 작성
- FMConstant 작성, 번들 ID 상수화
- 기존 로거 및 print 새로운 로거로 대체
- 로거의 category를 설정하는 데 고민이 있었습니다.
- 현재 설정한 카테고리는 아래와 같습니다.
- general
- user
- device
- viewLifeCycle
- appLifeCycle
=> [iOS/#90] 공통 로거 작성

iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift
close #91 
FaceUp이 아닌 다른 Orientation일 때 faceupfeedback이 오는 것 수정
추가로 cancellable 변수 오타 수정
=> [iOS#91] FaceUp이 아닌 다른 Orientation일 때 faceupfeedback이 오는 것 수정

iOS/FlipMate/FlipMate/Common/Font/FlipMateFont.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift
close #64 
관리 버튼 다크모드 대응
추가로 타이머 디스플레이 크기를 일단 크게 해보았습니다.
=> [iOS#64] 버튼 다크모드 대응

BE/src/app.module.ts, BE/src/auth/auth.controller.spec.ts, BE/src/auth/auth.controller.ts, BE/src/auth/auth.module.ts, BE/src/auth/auth.service.spec.ts, BE/src/auth/auth.service.ts, BE/src/google.strategy.ts, BE/src/users/users.module.ts, BE/src/users/users.service.spec.ts, BE/src/users/users.service.ts
close #21 
- google 서버로부터 받아온 AccessToken기반 User생성
- 구글 로그인 및 회원가입 성공시 jwt토큰 반환
=> [BE#21] google OAuth 로그인

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Presentation/TimerScene/Model/Category.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/CategoryViewModel.swift
close #97 
- 카테고리 구조체 추가
- 카테고리 뷰 모델 추가
- 카테고리 구조체에는 당장 필요한 색상, 과목명, 학습 시간 정도만 넣어두었습니다. 서버와 통신 시 UUID 등도 필요할까요?
- 뷰 모델을 구현하면서 Dictionary로 할 경우 Key 값이 과목명이 되는 것은 조금 이상한 것 같아 우선 Array로 index 활용하게 끔 하였습니다. 후에 UUID 등을 추가해본다면 Key로 활용해서 Dictionary로 바꿔도 될 듯 싶은데 뭐가 좋을까요?
+)
추가로 카테고리 뷰모델에 넣어야할 Input/Output이 있다면 말씀해주세요
=> [iOS#97] category model 구현

BE/src/categories/categories.entity.ts, BE/src/study-logs/dto/request/create-study-logs.dto.ts, BE/src/study-logs/dto/response/study-logs.dto.ts, BE/src/study-logs/study-logs.controller.ts, BE/src/study-logs/study-logs.entity.ts, BE/src/study-logs/study-logs.service.ts, BE/src/users/entity/users.entity.ts
close #119 
- 학습 기록 추가
- 학습 기록 조회
- 학습 기록 삭제
카테고리에서 했던 방식으로 처리했습니다
entity 파일에 eager 옵션으로 처리했습니다
=> [BE#119] 학습 기록 추가, 조회, 삭제

iOS/FlipMate/FlipMate/Presentation/TabBarViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/TimerViewModel.swift
closed #137 
- 카테고리 관리 버튼 클릭시 카테고리 화면 Push 구현
=> [iOS#137] 카테고리 관리 버튼 클릭 시 화면 이동

BE/src/main.ts
close #122 
- SSL인증서 추가 httpOtions작성
=> [BE#122] SSL인증서 추가 httpOtions작성

.github/workflows/be-pre-production-workflow.yaml, BE/src/main.ts
=> [BE#152]cd pre production

.github/workflows/be-main-workflow.yaml
=> [BE#161] 메인 브랜치 cd

BE/src/auth/auth.service.ts
=> [BE#168] nickname 버그

BE/src/categories/categories.controller.ts, BE/src/categories/categories.service.ts, BE/src/categories/dto/response/category.dto.ts, BE/src/study-logs/study-logs.entity.ts
=> [BE#170] user id기반으로 조회하도록 버그 수정

BE/package-lock.json, BE/package.json, BE/src/auth/auth.controller.ts, BE/src/common/logging.config.ts, BE/src/common/logging.interceptor.ts, BE/src/main.ts
close #151 
- logger 구현
- iOS 테스트용 auth/google/app 컨트롤러 작성
=> [BE#151] logger구현

BE/src/auth/auth.controller.ts, BE/src/auth/auth.service.ts, BE/src/categories/categories.controller.ts, BE/src/common/utils.ts, BE/src/study-logs/dto/request/create-study-logs.dto.ts, BE/src/study-logs/study-logs.controller.ts, BE/src/study-logs/study-logs.entity.ts, BE/src/study-logs/study-logs.service.ts
- typeOrm의 queryBuilder를 통해 그룹핑 및 합계 계산
- 구글 앱 로그인 오류 수정
=> [BE#178] 학습기록 groupby category

BE/src/main.ts, BE/src/study-logs/study-logs.controller.ts
=> [BE#181] 의도치 않은 커밋 되돌리기

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Data/Network/BaseComponents.swift, iOS/FlipMate/FlipMate/Data/Network/DataMapping/TimerScene/StudyLogResponseDTO.swift, iOS/FlipMate/FlipMate/Data/Network/MockURLSession.swift, iOS/FlipMate/FlipMate/Data/Network/StudyLogEndpoints.swift, iOS/FlipMate/FlipMate/Data/Network/TimerEndpoints.swift, iOS/FlipMate/FlipMate/Data/Repositories/DefaultCategoryRepository.swift, iOS/FlipMate/FlipMate/Data/Repositories/DefaultStudyLogRespository.swift, iOS/FlipMate/FlipMate/Domain/Entities/Category.swift, iOS/FlipMate/FlipMate/Domain/Entities/StudyLog.swift, iOS/FlipMate/FlipMate/Domain/Repositories/StudyLogRepository.swift, iOS/FlipMate/FlipMate/Domain/UseCases/DefaultStudyLogUseCase.swift, iOS/FlipMate/FlipMate/Domain/UseCases/Protocol/StudyLogUseCase.swift, iOS/FlipMate/FlipMate/NetworkService/Requestable.swift, iOS/FlipMate/FlipMate/Presentation/Mocks/StduyLogMock.swift, iOS/FlipMate/FlipMate/Presentation/TabBarViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/Model/CategorySettingSection.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/View/CategoryListCollectionViewCell.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/CategorySettingViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/TimerViewModel.swift
closed #176 
- DiffableDataSource을 통한 DataSource관리
- StudyLog Entity 구현
- UseCase, Repository 구현
- StudyLogMockResponse 구현
- 타이머 화면 유저 정보 바인딩 구현
- 추후에 작성하겠습니다.
=> [iOS#176] 타이머 화면 카테고리 및 사용자 정보 네트워킹 구현

BE/package-lock.json, BE/package.json, BE/src/app.module.ts, BE/src/study-logs/study-logs.service.ts
=> [BE#192] 특정 유저의 카테고리만 반환하도록 수정

BE/package-lock.json, BE/package.json, BE/src/app.module.ts, BE/src/study-logs/study-logs.service.ts
=> [BE#배포] 배포

iOS/FlipMate/FlipMate/Application/SceneDelegate.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewModel/LoginViewModel.swift
closed #188 
- keyChain 중복 저장 버그 수정
아직 로그이웃과 토큰 만료 상태처리 미구현인 상태로 생기는 KeyChain 중복 저장에러를 임시방편으로 해결하였습니다~
=> [iOS#188] keyChain 중복 저장 버그 수정

iOS/FlipMate/FlipMate/Data/Network/DataMapping/TimerScene/StudyLogResponseDTO.swift, iOS/FlipMate/FlipMate/Data/Repositories/DefaultCategoryRepository.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/View/CategoryListCollectionViewCell.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift, iOS/FlipMate/Podfile.lock
- 다크모드 cell 클릭 백그라운드 색상 대응
- 카테고리 관리 화면 cell 시간 표시 이슈 대응
- StudyLogResponseDTO 수정
=> [iOS/Hotfix] 3주차 배포 전 긴급 버그 수정

BE/package-lock.json, BE/package.json, BE/src/app.module.ts, BE/src/study-logs/study-logs.service.ts, iOS/FlipMate/FlipMate/Application/SceneDelegate.swift, iOS/FlipMate/FlipMate/Data/Network/DataMapping/TimerScene/StudyLogResponseDTO.swift, iOS/FlipMate/FlipMate/Data/Repositories/DefaultCategoryRepository.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewModel/LoginViewModel.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/View/CategoryListCollectionViewCell.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift, iOS/FlipMate/Podfile.lock
=> [iOS#배포] 3주차 데모 배포 

iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift
- NotificationCenter remove 추가
=> [iOS/hotfix] NotificationCenter remove 추가

BE/src/users/users.service.ts
=> [BE/#228] 사라진 괄호 넣어주기

BE/package-lock.json, BE/package.json, BE/src/auth/auth.controller.ts, BE/src/auth/auth.service.ts, BE/src/auth/google.strategy.ts, BE/src/common/multer.config.ts, BE/src/common/s3.service.ts, BE/src/users/users.module.ts, BE/src/users/users.service.ts
close #240 
- resizing이후에 S3업로드
- 이미지 유해 검사 서비스 연결
- image_url이 null일때 기본 이미지 설정
- sharp를 통한 이미지 리사이징
- 기존에 multer-s3 storage대신 memory-storage사용 이후에 서비스에서 로직 처리
=> [BE#240] resizing filter 프로필 이미지

BE/src/common/redis.service.ts, BE/src/mates/mates.controller.ts, BE/src/mates/mates.module.ts, BE/src/mates/mates.service.ts, BE/src/study-logs/study-logs.module.ts, BE/src/study-logs/study-logs.service.ts
close #124 
- redis로부터 친구 학습여부 조회
- 조회시 Promise all을 통해 비동기처리
=> [BE#124] 친구 상태 조회

BE/src/users/users.controller.ts, BE/src/users/users.service.ts
close #248
- 닉네임 검색으로 친구 프로필 이미지 응답
=> [BE#248] 닉네임 검색으로 프로필 이미지 url 응답

BE/src/users/users.service.ts
close #251 
- 유저 프로필 URL로 응답하도록 수정
=> [BE#251] 유저 프로필 URL로 응답하도록 수정

BE/src/auth/auth.controller.ts, BE/src/users/users.service.ts
close #255 
이미지가 null일때 분기처리 하였습니다!
=> [BE#255] 이미지 null일때 분기처리

iOS/FlipMate/FlipMate/Data/Network/TimerEndpoints.swift
=> [iOS#hotfix] 타이머 시작 종료 DTO 수정

iOS/FlipMate/FlipMate/Data/Network/TimerEndpoints.swift
=> [배포] 4주차 1차 배포

BE/src/study-logs/study-logs.service.ts
close #269 
학습 기록이 없는 경우 학습 시간 0을 반환하도록
=> [BE#269] 학습 기록이 없는 경우 학습 시간 0을 반환하도록

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Application/DIContainer/SocialDIContainer.swift, iOS/FlipMate/FlipMate/Application/DIContainer/TabBarDIContainer.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/Flow/SocialFlowCoordinator.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/FriendAddViewController.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/SocialViewController.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewModel/FriendAddViewModel.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewModel/SocialViewModel.swift, iOS/FlipMate/FlipMate/Presentation/TabBar/Flows/TabBarFlowCoordinator.swift, iOS/FlipMate/Podfile.lock
closed #273 
- SocialFlowCoordinator 구현
- SocialDIConatiner 구현
- 친구추가 버튼 클릭시 친구 추가 화면으로 이동
- 닫기 버튼 클릭시 이전 화면으로 dismiss
- 친구 추가 완료시 이전 화면으로 dismiss
없슴다
=> [iOS#273] 소셜 Scene Coordinator 통한 화면 전환

BE/src/categories/categories.entity.ts, BE/src/study-logs/study-logs.entity.ts
close #276 
- entity에 class validator 추가
시간, 컬러 코드 등은 `@Mates`와 정규표현식으로 처리
=> [BE/#276] entity에 class validator 추가

BE/src/mates/mates.controller.ts
=> [BE#279]  친구 추가 응답 수정

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Presentation/MyPageScene/MyPageViewController.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/SocialViewController.swift
close #285 
- 임시 로그아웃 버튼 생성 및 마이페이지와 연결
=> [iOS/#285] 임시 로그아웃 버튼 생성 및 연결

iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/SocialViewController.swift
- 아이폰 12이하 기종에서 공부시간 짤리던 이슈 수정
=> [iOS#hotfix] 공부시간 Label 이슈 수정

iOS/FlipMate/FlipMate/Data/Network/DataMapping/SocialScene/FriendsResponseDTO.swift
=> [iOS#hotfix]FriendsResponseDTO 수정

BE/src/mates/mates.service.spec.ts, BE/src/mates/mates.service.ts, BE/src/study-logs/study-logs.service.ts, BE/test/mock-repo/mock-categories-repo.ts, BE/test/mock-repo/mock-mates-repo.ts, BE/test/mock-repo/mock-user-repo.ts, BE/test/mock-service/mock-redis-service.ts, BE/test/mock-service/mock-study-logs-service.ts, BE/test/mock-service/mock-user-service.ts, BE/test/mock-table/categories.json, BE/test/mock-table/study-logs.json, BE/test/mock-table/users.json
close #212 
- mates 서비스에 대한 테스트 코드 작성
- 그 과정에서 발견한 에러 수정
기존 api에서 길이가 6인 배열을 응답으로 던져줘서 이 부분 수정했습니다
그 외에는 테스트 코드에 필요한 메서드만 mocking 해서 활용했습니다
=> [BE#212] mates 서비스에 대한 테스트 코드 작성

iOS/FlipMate/FlipMate/Presentation/SocialScene/View/SocialChartView.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/SocialDetailViewController.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewModel/SocialDetailViewModel.swift
close #299 
viewModel property에 직접 접근하던 로직 수정
차트에 axis label 추가 및 위치 변경
1. 차트가 특정 조건에 안나오던 버그는 백엔드간 통신 오류였습니다! 해결 했습니다
2. `$` prefix 사용하여 published property binding 해 주었습니다.
3. Chart Y축을 분으로 바꾸고 label 추가해두었습니다. 적게 공부하면 차트에 조금 어색하게 나와서 float minute으로 지정해두었습니다.
=> [iOS/#299] 소셜 상세 화면 완료

iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift
close #309 
- setBrightness 함수 및 연관 프로퍼티 제거 
- https://yeim.notion.site/Faceup-0cfad667e90743dab306cf013e280f72?pvs=4
- 피어 세선 때 설명드릴게요! 더 좋은 방법이 있다면 이야기해보면 좋겠습니당
=> [iOS#309] 화면 밝기 조절 기능 제거

BE/.gitignore, BE/src/admin/admin.controller.spec.ts, BE/src/admin/admin.controller.ts, BE/src/admin/admin.module.ts, BE/src/app.module.ts, BE/src/auth/auth.service.ts, BE/src/categories/categories.service.ts, BE/src/common/const/service-var.const.ts, BE/src/common/interceptor/logging.interceptor.ts, BE/src/common/middleware/logging.middleware.ts, BE/src/common/redis.service.ts, BE/src/mates/mates.controller.ts, BE/src/mates/mates.module.ts, BE/src/mates/mates.service.ts, BE/src/study-logs/study-logs.service.spec.ts, BE/src/study-logs/study-logs.service.ts, BE/test/load-performance/loadtest-categories.js, BE/test/load-performance/loadtest-study.js, BE/test/load-performance/loadtest.js
close #330 
- k6를 통해 지연시간 및 처리량 테스트를 위한 환경 구축
- 여러 사용자를 위한 목유저 생성 스크립트 작성
- 목유저를 DB에 작성하기 위한 ADMIN API 작성
=> [BE#330] 성능테스트 환경 구축

iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/TimerViewModel.swift
closed #302 
- 공부 종료 화면 이동 시 근접거리 센서 및 자이로 MotionManager 비활성화
타이머 ViewController에서 공부 종료 ViewController로 넘어가더라도 
기존의 타이머 ViewController와 ViewModel이 메모리에 그대로 남아있어 디바이스 방향과 근접거리 센서가 공부 조건에 맞으면 작동됐었습니다.
이를 해결하기 위해서 TimerViewModel의 output으로 모션매니저와 근접거리센서를 활성화하거나 비활성화 하도록 수정했습니다.
viewWillAppear시에는 TimerViewModel input으로 deviceSettingEnabledPublisher의 데이터 스트림에 true을 전달하고
viewDidDisAppear와 공부 종료 화면 이동시에는 deviceSettingEnabledPublisher의 데이터 스트림에 false을 전달해
ViewController가 해당 퍼블리셔를 바인딩하여 메소드를 통해 모션매니저와 근접거리센서를 설정해서 해결했습니다.
=> [iOS#302]공부 종료 화면에서 타이머 작동되던 이슈 해결

BE/src/auth/auth.controller.ts, BE/src/categories/categories.controller.ts, BE/src/common/response.dto.ts, BE/src/mates/mates.service.ts, BE/src/study-logs/dto/response/today-logs.dto.ts, BE/src/study-logs/dto/response/weekly-stats.dto.ts, BE/src/study-logs/study-logs.controller.ts
close #336 
- @ApiBearerAuth() 추가
- DTO 빠진 것들 추가
=> [BE#336] weekly-stats에 @ApiBearerAuth()추가

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/SocialViewController.swift
=> [iOS/hotfix] 컨플릭 누락 사항 수정

iOS/FlipMate/FlipMate/NetworkService/Provider.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewModel/LoginViewModel.swift
- 디바이스 로그인 버그 수정
- SignOutManager 옵셔널로 수정
\
=> [iOS#hotfix] 디바이스 로그인 버그 수정

BE/package-lock.json, BE/package.json, BE/test/load-performance/loadtest-social.js, BE/test/load-performance/loadtest-study.js
close #332 
- 소셜 기능 부하 테스트 코드 작성
- faker를 이용해서 학습 기록 부하 테스트 데이터 현실적인 데이터로 변경
- 소셜 기능 부하 테스트 데이터 현실적인 데이터 faker로 생성
- faker로 데이터 만드는거 작성 해보다가 일단 커밋 했습니다. 원래대로 돌리는건 쉬우니까..
- 소셜 기능에서 3초마다 폴링하는 걸 `setInterval`을 이용해서 처리했는데, 공식 문서에 `group` 안에서 비동기 함수 쓰지 않는걸 권장한다고 해서 `group` 없이 작성했습니다. `clearInterval` 안해주면 정상적으로 종료가 안돼서 이 부분도 처리해줬어요
=> [BE#332] 소셜 기능 k6 부하 테스트 코드 작성

BE/test/load-performance/loadtest-social.js, BE/test/load-performance/loadtest-stats.js
close #348
- scenarios 를 굳이굳이 써봤습니다. 저는 둘이 같은 옵션을 주긴 했는데, 각 시나리오마다 다른 옵션들 줄 때 용이할 것 같습니다..ㅎ
=> [BE#348] stats의 부하테스트 작성

BE/src/auth/auth.controller.ts, BE/src/common/config/multer.config.ts, BE/src/common/exception-filter/http-exception-filter.ts, BE/src/users/users.service.ts
close #358 
- 닉네임 중복 시 40000
- 유해한 이미지인 경우 40001
- 이미지 확장자가 다른 경우, AI 서버에서 인식하지 못하는 경우 40002
같은 400 에러여도 클라이언트에서 다르게 처리를 해줘야 하는 경우가 있어서 세분화 했습니다.
=> [BE#358] 유저 관련 에러 세분화

iOS/FlipMate/FlipMate/Presentation/SocialScene/Flow/SocialFlowCoordinator.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/View/SocialChartView.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/SocialDetailViewController.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewModel/SocialDetailViewModel.swift
close #345 
1. 소셜 상세 화면 modal 방식으로 변경
2. 소셜 상세 화면 차트에 스크롤 기능 추가
차트에만 스크롤 기능 추가하였습니다.
=> [iOS/#345] 소셜 상세 화면 수정

iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerFinishViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift
공부 저장 후 디바이스 뒤집을 시 타이머 작동안하던 버그 수정
=> [iOS#hotfix] 공부 저장 후 디바이스 뒤집을 시 타이머 작동안하던 버그 수정

iOS/FlipMate/FlipMate/Presentation/ChartScene/ViewController/ChartViewController.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/Flow/SocialFlowCoordinator.swift
=> [iOS#hotifx] 친구 언팔로우하면 dismiss 안되던 버그 수정

iOS/FlipMate/FlipMate/Presentation/Utils/Extensions/Date++Extension.swift, iOS/FlipMate/FlipMate/Presentation/Utils/FriendStatusPollingManager/FriendStatusPollingManager.swift
close #369 
- GMT로 Timezone 동기화
- Timer bug fix
=> [iOS/#369] Timezone 동기화 및 Timer bug fix

BE/src/mates/mates.service.spec.ts, BE/src/users/users.service.spec.ts, BE/test/mock-repo/mock-mates-repo.ts, BE/test/mock-service/mock-config-service.ts, BE/test/mock-table/users.json
close #215
- createUser() 테스트 코드 작성
- getUserProfileByNickname() 테스트 코드 작성
- updateUser() 테스트 코드 작성
외부 API 요청이랑 cdn 업로드는 작성하지 않았습니다
=> [BE#215] users 테스트 코드 작성

iOS/FlipMate/FlipMate/Presentation/ChartScene/View/CustomCalenderView.swift, iOS/FlipMate/FlipMate/Presentation/ChartScene/View/DailyChartView.swift, iOS/FlipMate/FlipMate/Presentation/ChartScene/View/WeeklyChartView.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/View/SocialChartView.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/SocialDetailViewController.swift, iOS/FlipMate/FlipMate/Presentation/Utils/FeedbackManager/FeedbackManager.swift
close #372 
Chart scrollView 추가
=> [iOS/#372] Chart scrollView 추가

iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/TimerFinishViewModel.swift
close #376 
타이머 종료 후 아니오 버튼 시 로직
=> [iOS/#376] 타이머 아니오 버튼 로직

iOS/FlipMate/FlipMate/PersistenceService/UserInfoStorage.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewController/SocialViewController.swift, iOS/FlipMate/FlipMate/Presentation/SocialScene/ViewModel/SocialViewModel.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/TimerViewModel.swift
closed #378 
- 소셜 화면 총 공부시간 동기화
- UserDefault을 통해서 총 공부시간을 동기화하였는데 추후에 프로필을 관리하는 매니저를 통해서 수정하도록 하겠습니다.
=> [iOS#378] 소셜 화면 총 공부시간 동기화

iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewController/SignUpViewController.swift, iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewModel/LoginViewModel.swift, iOS/FlipMate/FlipMate/Presentation/MyPageScene/Flow/MyPageFlowCoordinator.swift, iOS/FlipMate/FlipMate/Presentation/MyPageScene/ViewController/ProfileSettingsViewController.swift, iOS/FlipMate/FlipMate/Presentation/Utils/FeedbackManager/FeedbackManager.swift
- 프로필 닉네임 변경 키보드 제한 
- 회원가입시 키체인 저장안되는 문제 수정
=> [iOS/hotfix] 배포전 버그 수정

iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerFinishViewController.swift
close #410
타이머 종료 화면 개선
선택적으로 CornerRadius 적용,
HIG에 맞게 예, 아니오 위치 수정했는데 저희가 이미 적응해서 그런지 위치를 바꿔보니까 막상 어색하네요
=> [iOS/#410] 타이머 종료 화면 개선

iOS/FlipMate/FlipMate/Presentation/LoginScene/ViewController/LoginViewController.swift
close #412 
당장 쓰지 않는 버튼 숨기기
당장은 hidden 만 해두었습니다. 레이아웃 전부 바꾸는 건 조금 과하다고 생각해서요 ,,
=> [iOS/#412] 당장 쓰지 않는 버튼 숨기기

iOS/FlipMate/FlipMate/Presentation/SocialScene/View/SocialChartView.swift, iOS/FlipMate/FlipMate/Resources/ko.lproj/Localizable.strings
배포 전 핫픽스
- localized string 일부 수정
=> [iOS] 배포 전 핫픽스

iOS/FlipMate/FlipMate/Presentation/MyPageScene/ViewController/MyPageViewController.swift, iOS/FlipMate/FlipMate/Presentation/MyPageScene/ViewModel/MyPageViewModel.swift
closed #422 
- 마이페이지 데이터 초기화 및 문의하기 삭제
=> [iOS#422] 마이페이지 데이터초기화 및 문의하기 삭제

iOS/FlipMate/FlipMate/Presentation/MyPageScene/ViewController/MyPageViewController.swift, iOS/FlipMate/FlipMate/Resources/en.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ja.lproj/Localizable.strings, iOS/FlipMate/FlipMate/Resources/ko.lproj/Localizable.strings
close #404 
- alert 구현
- 다국어 지원
- 어느 정도의 애니메이션을 주면 좋을 듯 합니다
=> [iOS/#404] 로그아웃 버튼 탭 시 alert 구현

iOS/FlipMate/FlipMate/Presentation/MyPageScene/ViewController/ProfileSettingsViewController.swift, iOS/FlipMate/FlipMate/Presentation/TabBar/Flows/TabBarFlowCoordinator.swift
- 테스트를 위해 올린 압축 퀄리티 값을 정상화하였습니다.
=> [iOS/HotFix] 압축 퀄리티 개선

iOS/FlipMate/FlipMate/Presentation/TimerScene/Flows/TimerFlowCoordinator.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewController/TimerViewController.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/TimerFinishViewModel.swift, iOS/FlipMate/FlipMate/Presentation/TimerScene/ViewModel/TimerViewModel.swift, iOS/FlipMate/FlipMate/Presentation/Utils/UserInfoManager/UserInfoManager.swift
closed #394 
- 자정이 넘어간 경우 타이머 당일로 화면 바뀌도록 수정
이전에 회의했던 내용 그대로 적용하여 공부 기록을 저장했을 때 API을 호출하여 화면을 다시 구성하도록 수정했습니다!
=> [iOS#394] 자정이 넘어간 경우 타이머 당일로 화면 바뀌도록 수정 

BE/src/mates/mates.controller.ts, BE/src/mates/mates.service.spec.ts, BE/src/mates/mates.service.ts, BE/test/mock-table/users.json
close #441 
- 기존 api는 그대로 두고, mates에 새로운 컨트롤러 파서 findMate 함수 작성
- 이미 친구면 20002, 자기 스스로면 20001, 이상없으면 20000, 없으면 에러 반환
=> [BE#441] 친구 검색기능 상태코드

BE/src/mates/mates.service.ts
=> [BE#hotfix] 소셜 타임존 에러 수정

BE/src/mates/mates.service.ts, BE/src/study-logs/study-logs.service.ts
close #459 
- 친구 상세화면 친구의 주간 학습 카테고리 1위 응답
=> [BE#459] 친구 상세화면 친구의 주간 학습 카테고리 1위

BE/src/study-logs/study-logs.service.ts
close #459 
카테고리 없는 경우 / 기타가 가장 많은 경우 구분
=> [BE#459] 카테고리 없는 경우 / 기타가 가장 많은 경우 구분

BE/src/categories/categories.service.ts
close #465 
이미 존재하는 카테고리인 경우 에러
=> [BE#465]이미 존재하는 카테고리인 경우 에러

BE/src/auth/auth.controller.ts, BE/src/users/users.service.ts
close #468 
- authController에 deleteUser함수 작성
- userService에 remove함수 작성
=> [BE#468] user 삭제 api

README.md
- 멤버에 분야 나오도록 수정
- 기술스택 추가 (iOS분들도 추가하면 좋을거 같은데 몰라서 못함ㅠ 추가 변경 필요)
- 인프라 구조 ncloud버전으로 변경
- 데모? gif 추가
=> [ALL] README 3차 업데이트

iOS/FlipMate/FlipMate.xcodeproj/project.pbxproj
close #528 
- Feature 모듈 폴더 작성
- 없음!
=> [iOS#528] Feature 모듈을 위한 폴더링 작성
